### DISCUSSION TITLE
How to install cri-o with GPU support for Kubernetes Cluster

### DISCUSSION THREAD

**Discussion by rsoika** [cri-o/cri-o#8198] [Q&A] [answered]
Hello,
I have a running Kubernetes Cluster using worker nodes running cri-o. I plan to add an additional worker node with a GPU and the NVIDIA Toolkit and CUDA API installed. 
My question is if someone can explain how to make cri-o aware of the GPU? 

In a Docker-compose.yaml file it is necessary to extend the resource section like this:

```yaml
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

Thanks for any tips.

**Comment by haircommander** [comment]
I believe the only thing that is needed is you need to use the nvidia runtime, but https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#configuring-cri-o gives some instructions. Also, you need to request the gpus in the pod spec using device plugins

**Comment by rsoika** [comment, marked as answer]
Hi @haircommander , yes at least it was surprising simple. 
The only thing you need in a running Kubernets cluster is to install the [NVIDIA GPU Operator](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/getting-started.html). This can be done with a helm chart:

```
helm install --wait --generate-name \
        -n gpu-operator --create-namespace \
        nvidia/gpu-operator 
```

And this script will start the operator that is automatically installing the needed drivers. Or if you have already installed an nvidia driver on your worker node you can disable the installation of the driver by the operator:

```
helm install --wait --generate-name \
     -n gpu-operator --create-namespace \
     nvidia/gpu-operator \
     --set driver.enabled=false
```

It may take a while if the operator has updated all nodes. After that the only thing you need to do to use the GPU is setting the resource limits:


```yaml
...
        resources:
          limits:
            nvidia.com/gpu: 1
```
