### ISSUE TITLE
cri-o needs cni workaround

### ISSUE THREAD

**Issue by mike-nguyen** [cri-o/cri-o#1804]
**Description**
Port forwarding from the container to the host doesn't seem to be working.  I need to run with `hostNetwork: true` to workaround it.

I am using kubelet to deploy a static nginx pod with containerPort:80 and hostPort:80.  When kubelet is using docker, I can `curl http://localhost:80` and I get the nginx default page.  When I switch kubelet to run with crio, I can see the container running but `curl http://localhost:80` does not respond.  This is a similar issue I was seeing with exposing ports using podman.

cri-o might need a version of https://github.com/containers/libpod/pull/1431
mheon mentioned:
> You can probably vendor libpod's pkg/firewall and then modify your netns setup code to run it though you might need to store more information than you do right now, libpod already stores the whole CNI response CRI-O does not

**Steps to reproduce the issue:**
1. 
 ```
cat << EOF > /etc/kubernetes/manifests/static-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: docker.io/nginx
      ports:
        - name: web
          containerPort: 80
          hostPort: 80
EOF
```
2.
```
cat << EOF > /etc/kubernetes/kubeletconfig
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
clusterDomain: kube.local
clusterDNS: [10.254.0.10]
cgroupDriver: systemd
staticPodPath: /etc/kubernetes/manifests/
authorization:
  mode: AlwaysAllow
authentication:
  anonymous:
    enabled: true
  webhook:
    enabled: false
EOF
```
3.
start kubelet
`/usr/bin/hyperkube kubelet --config /etc/kubernetes/kubeletconfig --container-runtime=remote --container-runtime-endpoint=unix:///var/run/crio/crio.sock --runtime-request-timeout=10m`
4
`curl http://localhost:80`

**Describe the results you received:**
Cannot access the nginx container through the exposed host port

**Describe the results you expected:**
Able to access the nginx container through the exposed host port

**Additional information you deem important (e.g. issue happens only occasionally):**
Always happens

**Output of `crio --version`:**

```
crio version 1.11.4
cri-o-1.11.4-2.rhaos3.11.gite0c89d8.el7_5.x86_64
```
**Additional Environment Information**
RHCOS 4.0.5796 in AWS
