### ISSUE TITLE
mountPropagation: Bidirectional

### ISSUE THREAD

**Issue by mcronce** [cri-o/cri-o#1962]
**Description**
I'm not having luck using `mountPropagation: Bidirectional` on volumes with CRI-O.  I found #1247 while troubleshooting so unless there was a regression, I'm guessing there's an issue with my environment but I'm not real sure where to go in terms of troubleshooting.  I did validate that everything works correctly when I switch to Docker as my run-time.

I do have `MountFlags=shared` in a drop-in for crio.service, and I've validated that that does indeed work:
```
$ sudo systemctl show crio | grep MountFlags
MountFlags=shared
```

Any help on how to continue troubleshooting to get up and running would be appreciated :)

In case this detail is relevant - the "outer" volume is a `hostPath` and the "inner" volume is cephfs - the specific container I'm having this issue with is the CSI plugin for cephfs.

**Steps to reproduce the issue:**
1. Use `mountPropagation: Bidirectional` in a volume mount on a privileged container
2. Mount something else into a subdirectory of that volume mount

**Describe the results you received:**
When I run `mount` in the container, I see, as expected, that the subdirectory is a mountpoint - I can see the data in the mount as well.  However, when I run `mount` on the host, I do _not_ see the subdirectory as a mountpoint, nor do I see the data in the mount.

**Describe the results you expected:**
I expect to see inner mounts and their data both in the container and on the host.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
crio version 1.13.0
commit: "08ea5be92fb3a8f3a5dcdd1948f2891f756397e6-dirty"
```
```
crio version 1.12.0-dev
commit: "ed74efc8af284f786e041e8a98a910db4b2c0ec7-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare metal cluster running Fedora 29 as the host OS.  CRI-O 1.12 installed from the official Fedora repo, CRI-O 1.13 built from source, and Kubernetes 1.13 installed from https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64

**Comment by mrunalp** [comment]
Can you share you k8s yaml file? Thanks!

**Comment by mcronce** [comment]
Definitely, but let me migrate the settings to it first.  I'm, quite embarrassingly, still passing most of my config in as command-line arguments.

**Comment by mcronce** [comment]
```yaml
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
address: 0.0.0.0
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 2m0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 5m0s
    cacheUnauthorizedTTL: 30s
cgroupDriver: cgroupfs
cgroupsPerQOS: true
clusterDNS:
- 10.254.0.2
clusterDomain: cluster.local
configMapAndSecretChangeDetectionStrategy: Watch
containerLogMaxFiles: 5
containerLogMaxSize: 10Mi
contentType: application/vnd.kubernetes.protobuf
cpuCFSQuota: true
cpuCFSQuotaPeriod: 100ms
cpuManagerPolicy: none
cpuManagerReconcilePeriod: 10s
enableControllerAttachDetach: true
enableDebuggingHandlers: true
enforceNodeAllocatable:
- pods
eventBurst: 10
eventRecordQPS: 5
evictionHard:
  imagefs.available: 10%
  memory.available: 100Mi
  nodefs.available: 5%
  nodefs.inodesFree: 5%
evictionPressureTransitionPeriod: 5m0s
failSwapOn: false
featureGates:
  VolumeSnapshotDataSource: true
  CSINodeInfo: true
  CSIDriverRegistry: true
fileCheckFrequency: 20s
hairpinMode: promiscuous-bridge
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 20s
imageGCHighThresholdPercent: 85
imageGCLowThresholdPercent: 80
imageMinimumGCAge: 2m0s
iptablesDropBit: 15
iptablesMasqueradeBit: 14
kubeAPIBurst: 10
kubeAPIQPS: 5
makeIPTablesUtilChains: true
maxOpenFiles: 1000000
maxPods: 250
nodeLeaseDurationSeconds: 40
nodeStatusUpdateFrequency: 10s
oomScoreAdj: -999
podPidsLimit: -1
port: 10250
registryBurst: 10
registryPullQPS: 5
resolvConf: /etc/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 2m0s
serializeImagePulls: true
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 4h0m0s
syncFrequency: 1m0s
systemReserved:
  cpu: "3"
  memory: "9Gi"
volumeStatsAggPeriod: 1m0s
```

I have a 3-node cluster, all three nodes were all experiencing this problem.  That's the config from just one; the only differences between them have to do with resources, but if needed I can post up the other two as well.
