### ISSUE TITLE
hostport not freed after delete of pod

### ISSUE THREAD

**Issue by RohanKurane** [cri-o/cri-o#2342]
Hey @saschagrunert @mrunalp 

I am facing a strange error. 

I deploy a pod with ```hostport``` and created using ```type:portmap```.
 
Then when I try to ```kubectl delete``` the pod, and re-deploy the same pod with same name, I get the following error - 

```
Warning  FailedCreatePodSandBox  1m    kubelet, ip-xxxxxxxxx.ec2.internal  Failed create pod sandbox: rpc error: code = Unknown desc = failed to add hostport mapping for sandbox k8s_server_default_436fb151-71b1-11e9-b2d9-128d1a3304a4_0(7993b317dc75381c0ed08a75019fde6c2fe70aaf5697af6cc1f0e85c7afddfd6): cannot open hostport 50051 for pod k8s_server_default_436fb151-71b1-11e9-b2d9-128d1a3304a4_0_: listen tcp :50051: bind: address already in use
```

I do not believe I saw this error when I used docker.  Any idea what is going on ? 

Thanks
Rohan

**Comment by saschagrunert** [comment]
Hey @RohanKurane, can you provide us the pod configuration you applied so that we can reproduce the issue?

**Comment by RohanKurane** [comment]
@saschagrunert  

Here is the YAML file I try - 

```
apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: server
  labels:
    app: server                                    # 2
spec:                                                # 3
  containers:
    - image: 961663255966.dkr.ecr.us-east-2.amazonaws.com/cm-be-1-5:latest # 4
      name: server
      securityContext:
        allowPrivilegeEscalation: true
        privileged: true
        capabilities:
          add:
             - IPC_LOCK
      resources:
        requests:
          memory: "3Gi"                                 # 5
      ports:
        - containerPort: 50051                          # 6
          hostPort: 50051
      volumeMounts:
      - name: config-data
        mountPath: /tmp
  volumes:
  - name: config-data
    emptyDir: {}
```

In ```/var/log/messages``` I see the error in my first comment here. 

Thanks for your help
