### ISSUE TITLE
How to run a CRI-O container in priviliged mode ?

### ISSUE THREAD

**Issue by RohanKurane** [cri-o/cri-o#2363]
Hi,

My yaml deployment looks as follows - 
```
apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: server5
  labels:
    app: server5                                    # 2
spec:                                                # 3
  hostNetwork: true
  containers:
    - image: 961663255966.-2xxxxxxx
      name: server5
          securityContext:
        allowPrivilegeEscalation: true
        privileged: true
        capabilities:
          add:
             - IPC_LOCK
```

However I do not believe the container is running in privileged mode since I get errors such as "Operation not permitted" when I run certain operations in my application running on the container. 
Is there anything that overrides the above yaml setting perhaps in ```crio.conf``` ? or something I am missing ?

@saschagrunert

**Comment by RohanKurane** [comment]
Here is from ```crio.conf```
```
default_capabilities = [
    "CHOWN",
    "DAC_OVERRIDE",
    "FSETID",
    "FOWNER",
    "NET_RAW",
    "SETGID",
    "SETUID",
    "SETPCAP",
    "NET_BIND_SERVICE",
    "SYS_CHROOT",
    "KILL",
]
```

Is there anything that says allow everything ? The particular function i fail on is a pthread function to do a setschedparam

**Comment by RohanKurane** [comment]
Looking in 
```https://github.com/kubernetes-sigs/cri-tools/blob/99551e7e015d48612ea19b630a2cc86ec159fbe3/pkg/validate/security_context_linux.go```
There is code that determines if a container should run privileged or not. 

Any idea what I need to set and where for it to run privileged ?

**Comment by RohanKurane** [comment]
how about adding ```SYS_NICE``` to the default capabiilties section in crio.conf for set_schedparam ?

**Comment by RohanKurane** [comment]
The above did not seem to help. Unless I was suppose to stop and start the kubelet service across the change.

**Comment by haircommander** [comment]
Did you allow privileged in the pod yaml? also, how did you start k8s?

**Comment by saschagrunert** [comment]
I guess the kubelet option is `--allow-privileged=true` to generally allow it. Then a pod containing:

```yaml
spec:
  containers:
    - name: my-container
      securityContext:
        privileged: true
      ...
```

should have all permissions.

**Comment by RohanKurane** [comment]
@haircommander @saschagrunert 
This is a part of my pod yaml - 
```
apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: server5
  labels:
    app: server5                                    # 2
spec:                                                # 3
  hostNetwork: true
  containers:
    - image: xxxxxxx
      name: server5
          securityContext:
        allowPrivilegeEscalation: true
        privileged: true
```

So as you see, I do have ```privileged: true```

The commands I am executing are specific to my application (server5) that is running in the container. Specifically it fails on a system call for ``pthread_setschedparam()``` with "Operation Not Permitted". That made me feel the container is not running privileged.

**Comment by RohanKurane** [comment]
And here is from ```/etc/systemd/system/kubelet.service```

```
[Service]
ExecStart=/usr/bin/kubelet \
  --node-ip=xxx.xx.xx.xxx \
  --config=/etc/kubernetes/kubelet/config \
  --allow-privileged=true \
  --cloud-provider=aws \
  --container-runtime=remote \
  --container-runtime-endpoint=unix:///var/run/crio/crio.sock \
  --image-service-endpoint=unix:///var/run/crio/crio.sock \
  --network-plugin=cni \
  --root-dir=/etc/kubernetes/kubelet \
  --cert-dir=/etc/kubernetes/kubelet/pki \
  --register-node=true \
  --kubeconfig=/etc/kubernetes/kubelet/kubeconfig \
  --node-labels=runtime=crio
```

**Comment by RohanKurane** [comment]
@haircommander 
To answer your question about how I start k8s - This is an EKS k8s cluster running on AWS with CRI-O installed on the worker node. I then do the above pod deployment and the pod/container are created. However the application that needs to run on the container does a few calls to ```pthread_setschedparam``` which fail with "Operation not permitted" so my application never starts on the running container.

**Comment by mrunalp** [comment]
@RohanKurane Can you try adding `AllowPrivilegeEscalation`? Also, what distro are you running on? Is SELinux enabled?

**Comment by RohanKurane** [comment]
@mrunalp  
```AllowPrivilegeEscalation``` is set to true in the yaml deployment 
```
apiVersion: v1
kind: Pod                                            # 1
metadata:
  name: server5
  labels:
    app: server5                                    # 2
spec:                                                # 3
  hostNetwork: true
  containers:
    - image: xxxxxxx
      name: server5
          securityContext:
        allowPrivilegeEscalation: true
        privileged: true
```

I am using Ubuntu as my container base image. 

```selinux = true``` in ```/etc/crio/crio.conf``` on the worker node where the container should be running. 

Is that right ?
