### ISSUE TITLE
Add support for passing sandbox annotations to runtime

### ISSUE THREAD

**Issue by harche** [cri-o/cri-o#2402]
Recently I added a feature in `containerd` that enabled setting up a filter in `CRI/Containerd` to pass specific kubernetes pod/deployment annotations to OCI runtime annotations. 

OCI annotations can be used to set the sandbox related parameters. In the case of VM based runtimes, such as kata, this can be used to dynamically select the `vmdisk` or `initrd` that can be custom built for that container image.

 e.g. With ppc64le ultravisors' upcoming capability to run secure VM which need to be encrypted with the public key of target system, user can specifically intruct the runtime, like kata, to use a specific initrd on the system for the given container image. 

Kata already supports setting those values via OCI annotations, it's just that until now CRI wasn't setting it. The corresponding k8s pod.yaml looks something like this,

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: foobar-kat3
  "annotations": {
    "com.github.containers.virtcontainers.InitrdPath" : "/usr/share/kata-containers/custom-secure-vm.img",
    "com.github.containers.virtcontainers.InitrdHash" : "3971EBF11A18BCE250A282E6FF78739C9A0F7BCB9BC3552FE9CD8191E4A4DA573BB38983A47B2A86A63BFC4E41D3361D5D6AE1A1480BF3F27F730CC75FBC84DE" 
 }
spec:
  runtimeClassName: kataclass
  containers:
  - name: redis
    image: redis:latest 
```

more info on this work can be found in the containerd repo, https://github.com/containerd/cri/pull/1084

I believe this feature should also exist in `CRI-O`. 

**Steps to reproduce the issue:**
N/A

**Describe the results you received:**
N/A

**Describe the results you expected:**
N/A

**Additional information you deem important (e.g. issue happens only occasionally):**
Please check https://github.com/containerd/cri/pull/1084

**Output of `crio --version`:**
N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A
