### ISSUE TITLE
cri-o doesn't clean up ip addresses

### ISSUE THREAD

**Issue by Bruceforce** [cri-o/cri-o#2410]
**Description**
cri-o doesn't clean up ip addresses after namespace deletion. If I run the steps provided in
https://github.com/kubernetes/kubernetes/issues/57280#issuecomment-356431256 the problem is resolved. But I think the addresses should be cleaned up automatically. 

**Steps to reproduce the issue:**
1. run `while true; do ls -la /var/lib/cni/networks/cbr0/ | wc -l; sleep 10; done;` on the node where the deployment will be scheduled
1. Create a new namespace
1. Create a new deployment in that namespace 
1. Wait until the deployment is ready
1. Delete the namespace
1. Repeat the above until you run out of ip addresses

or in short:
run 
```
while true; do kubectl apply -f test.yml && kubectl rollout status deployment/nginx-deployment -n test && kubectl delete -f test.yml; done
``` 
on the master (see below for `test.yml` manifest)
run 
```
while true; do ls -la /var/lib/cni/networks/cbr0/ | wc -l; sleep 10; done;
``` 
on the node where the deployment will be scheduled

**Describe the results you received:**
When running `while true; do ls -la /var/lib/cni/networks/cbr0/ | wc -l; sleep 10; done;` the number just increases every time a new pod is created, but after the namespace (and so the pod) is deleted the number won't drop. If you repeat this a few times you will run out of ip addresses.

**Note:** I tried the same steps with cri-o, docker and containerd and this occured only using cri-o. See the images below.

**Describe the results you expected:**
The ip addresses should be freed if the pod is deleted.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
```
$ crio --version
crio version 1.14.2-dev
commit: "238229ea3b49a1add6e14e577e6e9e208ec0cf57"

$ kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:08:49Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

kubelet --version
Kubernetes v1.14.1

cni: flannel
```

**test.yml**
```
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        testNode: "true" #ensure that the deployment will be scheduled here
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Self-Hosted with kubeadm.

Here you can see the same test on cri-o and containerd. On the left is the deployment creation and deletion and on the right is `while true; do ls -la /var/lib/cni/networks/cbr0/ | wc -l; sleep 10; done;`
**cri-o**
![crio_2019-05-27 111916](https://user-images.githubusercontent.com/20187589/58411478-a8ea4d80-8074-11e9-9785-0f20560ec4ef.jpg)

**containerd**
![containerd_2019-05-27](https://user-images.githubusercontent.com/20187589/58412346-8fe29c00-8076-11e9-930b-96a8c35e8f90.jpg)

**Comment by saschagrunert** [comment]
Hey @Bruceforce, thanks for reporting the issue. May I ask you how the CNI configuration looks like and which version of CNI plugins you are using? Beside this, do you see error or warning messages within the CRI-O log? Thanks in advance! :pray:

**Comment by Bruceforce** [comment]
Hi @saschagrunert, thanks for the fast response.

```
# cat /etc/cni/net.d/10-flannel.conflist
{
  "name": "cbr0",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}
```

Somehow there isn't a `cniVersion` variable inside this file. Is this sufficient?

```
# apt-cache policy kubernetes-cni
kubernetes-cni:
  Installed: 0.7.5-00
  Candidate: 0.7.5-00
```

With `log_level = "error"` `systemctl -xeu crio` is empty.

**Comment by saschagrunert** [comment]
Today I took my time to try a reproduction of the issue with `k8s/kubernetes/hack/local-up-cluster.sh` and a bridged interface (v0.7.0 of CNI plugins). From my side every IP got cleaned up when running the same workloads and watching the interfaces like in the example.

I guess we have to dig deeper and test it again with flannel.

**Comment by Bruceforce** [comment]
Too bad. I'm having this issue inside a local testing environment using vagrant and inside another environment of proxmox VMs.

I just tested again in a clean environment with weavenet as CNI and I see the following files in `ls -la /var/lib/cni/results/`
```
...
cni-loopback-fb8b6d2b5566b7062bbb260000e5683d21d4ba91bb9a50ce6ca5bff3fcf96e19-lo
cni-loopback-fc4d5867851a7130a2eee30b18e7d6bb2d39cf03e5878ac5f5b625491dc517f3-lo
cni-loopback-fcab41f68be931c980b6d6be4ffe784f092d93d2fd8de40a33b15d0a03ca0628-lo
cni-loopback-fe536d1d8f1f444cc086bf434b4439ae1b7a83fb288ccfba76dcdc2c348ca7ba-lo
cni-loopback-fe8768875a77fffe409957ef53a0ed81ec293c7db051b4d370380228a57d889b-lo
weave-071a35211995e611a6c52907be6055ba088f57d67fef4fbb29279c9f23f61fd0-eth0
weave-08f8e098fab324619c80870b686dbd7ffb352c6bbbdef35edb0b84e1edffc310-eth0
weave-21d55e42f48dfe4d6c46b32966b4ce67263d76871843313bea8ac2a2bd59955e-eth0
weave-2cd5e5b9e555dd36e5a042ed956c023f387b5ce567d0490e5e04c109f0b8b4a4-eth0
...
```

The cni-loopback files seems to stay there when the deployment is deleted but the weave files are cleaned up after a little while.

Unfortunately I'm really no CNI expert, but if you have anything in mind that I should try you could let me know.

**Comment by saschagrunert** [comment]
> Too bad. I'm having this issue inside a local testing environment using vagrant and inside another environment of proxmox VMs.

Do you think you can provide me the vagrant file that I can reproduce the issue? 😇

**Comment by Bruceforce** [comment]
Here you go. The whole environment I use is a bit more complex (since it supports multiple CNIs, CRIs and is bootstrapped with kubeadm and ansible). So I removed the Vagrant shell provisioners in the zip. 

I use the following commands within ansible to bootstrap the cluster:

```
kubeadm init  --config /etc/kubernetes/kubeadm_init_config.yml \
                          --ignore-preflight-errors=SystemVerification"
sysctl net.bridge.bridge-nf-call-iptables
sysctl net.bridge.bridge-nf-call-iptables=1
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```

Since we run Vagrant with vbox there is this issue with the NAT adapter always being the first interface. So we need to patch the flannel daemonset `kube-flannel-ds-amd64` like the following

```
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: kube-flannel
          args:
          - [...]
          - --iface-regex=192.168.90
```

Let me know if you need anything else and I hope this is at least somehow comprehensible 😄 

[files.zip](https://github.com/cri-o/cri-o/files/3224575/files.zip)

**Comment by saschagrunert** [comment]
I was able to reproduce the issue with the flannel config you provided me. Can you please try to change it to:

```yml
{
  "name": "cbr0",
  "cniVersion": "0.3.0",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "hairpinMode": true,
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    }
  ]
}
```
