### ISSUE TITLE
crio reports names as null for old images that have no parent tag

### ISSUE THREAD

**Issue by cduchesne** [cri-o/cri-o#2454]
**Description**
When a new container image is pulled with the same tag as a previously existing image, the kubernetes status shows null as the `names` for the image. This should probably instead remove the labeled reference for the old image, but still maintain an image@sha256 reference.

**Steps to reproduce the issue:**
1) check status of node via kubernetes api
```
[root@master ~]# kubectl get node node01 -o yaml
apiVersion: v1
kind: Node
metadata:
  name: node01
spec:
  podCIDR: 10.100.0.0/24
status:
  images:
  - names:
    - docker.io/library/redis@sha256:478392fbb4f132b36b8ead3435087553ee7e6f0395b3d64987ae195268d13493
    - docker.io/library/redis:latest
    sizeBytes: 98259235
```

2) pull an updated image with same tag
```
[root@node01 ~]# crictl pull redis
Image is up to date for docker.io/library/redis@sha256:2720a72fb05febf7994e422b7cd327a031dcca2863a808e2825bf3cbb8d4c804
```

3) check updated status via kubernetes api
```
[root@master ~]# kubectl get node node01 -o yaml
apiVersion: v1
kind: Node
metadata:
  name: node01
spec:
  podCIDR: 10.100.0.0/24
status:
  images:
  - names:
    - docker.io/library/redis@sha256:2720a72fb05febf7994e422b7cd327a031dcca2863a808e2825bf3cbb8d4c804
    - docker.io/library/redis:latest
    sizeBytes: 98303778
  - names: null
    sizeBytes: 98259235
```

Once this status shows null for the name, it breaks compatibility with the spec. If you were to try and edit a node, and manually apply an annotation and save it, you would see an error that null is not an allowed value for names.

```
# nodes "node01" was not valid:
# * : Invalid value: "The edited file failed validation": ValidationError(Node.status.images[1]): missing required field "names" in io.k8s.api.core.v1.ContainerImage
```

This will impact anything that is doing validation on the node.status from the received objects. My example is just the simplest way to demonstrate.

**Output of `crio --version`:**
I have tested this in 1.11.12-dev and the latest of 1.14 release branch.
```
# crio --version          
crio version 1.14.3-dev
commit: "615c561b67ac140c1d155d9dc25767a0e81ce433"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
virtualbox for example above, but should work in any environment
