### ISSUE TITLE
Can't start without `runc` binary

### ISSUE THREAD

**Issue by AkihiroSuda** [cri-o/cri-o#3360]
**Description**

CRI-O can't start up without `runc` binary, even if there is no runtime handler for runc.

**Steps to reproduce the issue:**
Start CRI-O with the following config, and without `runc` binary in the `$PATH`:

```toml
[crio.runtime]
  default_runtime = "crun"
  [crio.runtime.runtimes]
    [crio.runtime.runtimes.crun]
      runtime_path = ...
      runtime_root = ...
```

**Describe the results you received:**
```
FATA[2020-03-06 00:56:24.238914386+09:00] Validating runtime config: runtime validation: "runc" not found in $PATH: exec: "runc": executable file not found in $PATH 
```

**Describe the results you expected:**
Should start up

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 
Version:       1.18.0-dev
GitCommit:     d0665fd81f4a651d6b4c6a480d2b598b18c93f4f
GitTreeState:  clean
BuildDate:     2020-03-05T14:20:58Z
GoVersion:     go1.13.8
Compiler:      gc
Platform:      linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Usernetes (https://github.com/rootless-containers/usernetes/pull/128)
