### ISSUE TITLE
Unable to add drop in config for kata runtime 

### ISSUE THREAD

**Issue by harche** [cri-o/cri-o#3536]
**Description**

if you leave the default `/etc/crio/crio.conf.d/00-default.conf` untouched and try to add a kata runtime drop in config say, `50-kata.conf` crio fails with following error,
```bash
$ cat /etc/crio/crio.conf.d/50-kata.conf
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```
```bash
#./crio
FATA[2020-04-07 15:18:12.097027625+05:30] Validating runtime config: default_runtime set to "runc", but no runtime entry was found for it 
```

If I comment out runc related sections from /etc/crio/crio.conf.d/00-default.conf ,
```toml
#[crio.runtime.runtimes.runc]
#runtime_path = ""
#runtime_type = "oci"
#runtime_root = "/run/runc"
```
and append it to 50-kata.conf ,
```toml
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"
```
crio comes up fine.
```bash
#./crio
WARN[2020-04-07 15:23:33.538555837+05:30] Skipping invalid hooks directory: stat /usr/share/containers/oci/hooks.d: no such file or directory 
INFO[2020-04-07 15:23:33.538625571+05:30] No seccomp profile specified, using the internal default 
INFO[2020-04-07 15:23:33.538634284+05:30] AppArmor is disabled by the system or at CRI-O build-time 
WARN[2020-04-07 15:23:33.540659588+05:30] Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled 
INFO[2020-04-07 15:23:33.549800080+05:30] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist 
INFO[2020-04-07 15:23:33.549827144+05:30] Update default CNI network name to podman    
WARN[2020-04-07 15:23:33.558814024+05:30] Error parsing metadata for fe5bcf80fbe5a549bbbfe9f7c291550ae895f6e625f223a7740a72ea46c17b86: unexpected end of JSON input, ignoring 
WARN[2020-04-07 15:23:33.559496090+05:30] Error parsing metadata for 85fcb82f7fe6e99ea09c841732416d29178cc7c333f2b9979233da890c92df9b: unexpected end of JSON input, ignoring 
```

**Steps to reproduce the issue:**
1. create a crio drop in file for kata runtime, 
```bash
$ cat /etc/crio/crio.conf.d/50-kata.conf 
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```
2. restart crio

**Describe the results you received:**
```bash
#./crio
FATA[2020-04-07 15:18:12.097027625+05:30] Validating runtime config: default_runtime set to "runc", but no runtime entry was found for it 
```

**Describe the results you expected:**
crio should have started with `runc` and `kata` both runtimes enabled. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**
clone from master 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by harche** [comment]
I will try to look into the code that tries to merge drop in config with the config with `/etc/crio/crio.conf.d/00-default.conf`

**Comment by saschagrunert** [comment]
Hey @harche yeah the issue is that we overwrite the whole map and not merge it. I think if we make the map merging more custom than this could work somehow, but we have to add additional logic. If you want then I can support you with that :)

**Comment by harche** [comment]
@saschagrunert Thanks, I appreciate your help. I am looking into the source to see where can we add that additional logic. If you have more concrete idea on how to fix this, feel free to take over.

**Comment by harche** [comment]
@saschagrunert thanks for your input. If I comment out the deletion [here](https://github.com/cri-o/cri-o/blob/c92cabd040564ca134c9b2a809f1d228143cbf67/pkg/config/config.go#L448) it resolves the issue reported here. However, if user wants to set the default runtime to kata it doesn't update the `default_runtime` field in the final config.

So after disabling deletion mentioned above, if I add the following drop in file
```toml
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```
the final crio config has, 
```toml
default_runtime = "runc"
[crio.runtime.runtimes.kata-qemu]
runtime_path = "/usr/bin/kata-runtime"
runtime_type = ""
runtime_root = ""

[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"
```
Which is perfect! But If set `default_runtime` in drop in config,
```toml
default_runtime = "kata-qemu"
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```
I was expecting the final crio config will have updated `default_runtime`, but I still see it set to the old value `runc`. 

Looking into it.

**Comment by harche** [comment]
```toml
[crio.runtime]
default_runtime = "kata-qemu"
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```
This drop in config file adds the runtime as well as sets the default runtime. I still have to [delete](https://github.com/cri-o/cri-o/blob/c92cabd040564ca134c9b2a809f1d228143cbf67/pkg/config/config.go#L448) this line though.

**Comment by harche** [comment]
```toml
[crio.runtime]
default_runtime = "kata-qemu"
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```

This drop in config file adds the runtime as well as sets the default runtime. I still have to delete this line though.

**Comment by harche** [comment]
So after deleting that [line](https://github.com/cri-o/cri-o/blob/c92cabd040564ca134c9b2a809f1d228143cbf67/pkg/config/config.go#L448), the behavior is as follows,

If user specifies the `default_runtime` in the drop in config file, 
```toml
[crio.runtime]
default_runtime = "kata-qemu"
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```
then the final crio file ends up having the `default_runtime` updated with the value specified in the drop in config (which in this example would be `kata-qemu`)
```toml
[crio.runtime]
default_runtime = "kata-qemu"

[crio.runtime.runtimes.kata-qemu]
runtime_path = "/usr/bin/kata-runtime"
runtime_type = ""
runtime_root = ""

[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"
```

On the other hand, if the user doesn't specify `default_runtime`in drop in config,
```toml
[crio.runtime.runtimes.kata-qemu]
runtime_path="/usr/bin/kata-runtime"
```

Then the final crio config will add the runtime details but will retain the old value of the `default_runtime`
``` toml
[crio.runtime]
default_runtime = "runc"

[crio.runtime.runtimes.kata-qemu]
runtime_path = "/usr/bin/kata-runtime"
runtime_type = ""
runtime_root = ""

[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"
```

@saschagrunert what do you think? If you are fine by it, I can send the PR.
