### ISSUE TITLE
kubeadm v1.18 fails to install static control plane pods with CRI-O runtime due to create sandbox error "name is reserved"

### ISSUE THREAD

**Issue by ghglza** [cri-o/cri-o#3571]
**Description**
kubeadm v1.18 fails to install static control plane pods with CRI-O runtime due to create sandbox error "name is reserved"

**Steps to reproduce the issue:**
1. build CRI-O from source branch release-1.18 (we tried several commits including 9cc38861d
2. try to provision k8s (version v1.18.0 or v1.18.1) cluster with kubeadm 

**Describe the results you received:**
kubelet tries to start k8s control plane pods as static pods.
This fails, apparently because CRI-O cannot create sandboxes with error

```
Apr 14 12:50:32 master1.corp.int crio[58767]: time="2020-04-14 12:50:32.758989506+02:00" level=info msg="Attempting to run pod sandbox with infra container: kube-system/kube-apiserver-master1/POD" id=c4c851f5-dde8-4433-86a6-cd8fa4011cd9 name=/runtime.v1alpha2.RuntimeService/RunPodSandbox
Apr 14 12:50:32 master1.corp.int crio[58767]: time="2020-04-14 12:50:32.759109234+02:00" level=warning msg="Error reserving pod name k8s_kube-apiserver-master1_kube-system_2abe36c990c315f116840d96b89eb8a2_0 for id 437508876cf392821439da52786df1f4ac3af41ca2501205e46478be5ec8d32f: name is reserved"
```
"crictl ps -a" generates no output.

**Describe the results you expected:**
CRI-O should be able to start the static pods, as with prior versions of k8s

**Additional information you deem important (e.g. issue happens only occasionally):**
This bug is reproducible for us, i.e. we were not able to bring up a v1.18 k8s cluster with CRI-O as runtime

**Output of `crio --version`:**
```
crio version
Version:       1.18.0-dev
GitCommit:     9cc38861d6a865f48e845267e9dc715e73a64ad2
GitTreeState:  clean
BuildDate:     2020-04-14T07:34:22Z
GoVersion:     go1.14.2
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic

```
conmon is version v2.0.15

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS is Centos 7, platform VMWare, CNI is kube-router

CRI-O configuration:
```
$ grep -v -e '^#' -e '^$' /etc/crio/crio.conf
[crio]
log_dir = "/var/log/crio/pods"
version_file = "/var/run/crio/version"
[crio.api]
listen = "/var/run/crio/crio.sock"
stream_address = "127.0.0.1"
stream_port = "0"
stream_enable_tls = false
stream_tls_cert = ""
stream_tls_key = ""
stream_tls_ca = ""
grpc_max_send_msg_size = 16777216
grpc_max_recv_msg_size = 16777216
[crio.runtime]
default_runtime = "runc"
no_pivot = false
decryption_keys_path = "/etc/crio/keys/"
conmon = "/usr/libexec/crio/conmon"
conmon_cgroup = "system.slice"
conmon_env = [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
]
selinux = false
seccomp_profile = ""
apparmor_profile = "crio-default"
cgroup_manager = "systemd"
default_capabilities = [
	"CHOWN",
	"DAC_OVERRIDE",
	"FSETID",
	"FOWNER",
	"SETGID",
	"SETUID",
	"SETPCAP",
	"NET_BIND_SERVICE",
	"KILL",
]
default_sysctls = [
]
additional_devices = [
]
hooks_dir = [
	"/usr/share/containers/oci/hooks.d",
]
default_mounts = [
]
pids_limit = 1024
log_size_max = -1
log_to_journald = false
container_exits_dir = "/var/run/crio/exits"
container_attach_socket_dir = "/var/run/crio"
bind_mount_prefix = ""
read_only = false
log_level = "warn"
log_filter = ""
uid_mappings = ""
gid_mappings = ""
ctr_stop_timeout = 30
manage_ns_lifecycle = false
namespaces_dir = "/var/run"
pinns_path = ""
[crio.runtime.runtimes.runc]
runtime_path = ""
runtime_type = "oci"
runtime_root = "/run/runc"
[crio.image]
registries = ["private-registry1.corp.int:54231",]
default_transport = "docker://"
global_auth_file = ""
pause_image = "k8s.gcr.io/pause:3.1"
pause_image_auth_file = ""
pause_command = "/pause"
signature_policy = ""
image_volumes = "mkdir"
[crio.network]
network_dir = "/etc/cni/net.d/"
plugin_dirs = [
	"/opt/cni/bin/",
]
[crio.metrics]
enable_metrics = true
metrics_port = 9090

```

kubeadm configuration:
```
---
apiVersion: kubeadm.k8s.io/v1beta2
nodeRegistration:
  criSocket: unix:///var/run/crio/crio.sock
  kubeletExtraArgs:
    log-dir: /var/log
    log-file: kubelet.log
    runtime-cgroups: /systemd/system.slice
  name: master1
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.1.79
  bindPort: 6443

---
apiServer:
  extraArgs:
    feature-gates: TTLAfterFinished=true
    service-node-port-range: 49152-65535
apiVersion: kubeadm.k8s.io/v1beta2
certificatesDir: /etc/kubernetes/pki
clusterName: infra-k8s.corp.int
controlPlaneEndpoint: 192.168.1.79
controllerManager:
  extraArgs:
    feature-gates: TTLAfterFinished=true
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/etcd
kind: ClusterConfiguration
kubernetesVersion: v1.18.1
networking:
  dnsDomain: infra-k8s.corp.int
  podSubnet: 172.24.0.0/16
  serviceSubnet: 172.25.0.0/16
scheduler: {}

---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
clusterCIDR: 172.24.0.0/16
kind: KubeProxyConfiguration
portRange: 49152-65535
mode: ipvs

---
apiVersion: kubelet.config.k8s.io/v1beta1
clusterDomain: infra-globo-k8s.nbg.sdv.sdvrz.de
cgroupDriver: systemd
clusterDNS:
- 172.25.0.10
evictionHard:
  imagefs.available: 5%
  nodefs.available: 5%
evictionSoft:
  imagefs.available: 5%
  nodefs.available: 5%
evictionSoftGracePeriod:
  imagefs.available: 10h
  nodefs.available: 10h
evictionPressureTransitionPeriod: 10h
hairpinMode: hairpin-veth
kind: KubeletConfiguration
podCIDR: 172.24.0.0/16
kubeletCgroups: /systemd/system.slice
```
