### ISSUE TITLE
Exec(sync) overwrites runtime spec args

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#3988]
**Description**

It looks like that an exec request overwrites the in-memory args for the container. This seems not harmful but leads into wrong information when running `crictl inspect`.

**Steps to reproduce the issue:**
1. Start CRI-O and kubernetes.
2. Apply the demo workload:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: insp
spec:
  containers:
    - name: insp
      image: fedora:latest
      args:
        - /bin/sh
        - -c
        - sleep infinity
```
3. Check the args:
```
> sudo crictl inspect 6c52fd7758503 | rg args -A3
        "args": [
          "/bin/sh",
          "-c",
          "sleep infinity"
```
4. Run an exec:
```
> sudo crictl exec 6c52fd7758503 echo test
test
```
5. Check the args:
```
> sudo crictl inspect 6c52fd7758503 | rg args -A3
        "args": [
          "echo",
          "test"
        ],
```
6. If we restart CRI-O, then the correct args will be loaded from disk again.

**Additional information you deem important (e.g. issue happens only occasionally):**

- Kubernetes and CRI-O latest master

Is this a bug or intended behavior? If we agree that this is a bug then I'll continue with working on a fix.

Refers to https://github.com/kubernetes-sigs/cri-tools/issues/642
