### ISSUE TITLE
runtimeVM: Logs in /var/log/pods/$namespace_$pod_name_$pod_uid/$container_name/$restart_number.log are empty

### ISSUE THREAD

**Issue by fidencio** [cri-o/cri-o#4081]
**Description**
While debugging #4029 I realised the content of `/var/log/pods/$namespace_$pod_name_$pod_uid/$container_name/$restart_number.log` is always empty.
After bisecting the issue, I found out that https://github.com/cri-o/cri-o/commit/924a8e9830f112821f03984d417f938f945ba442 is the faulty commit, that makes the logs to not be stored anymore.

**Steps to reproduce the issue:**
reproducer.yaml:
```
apiVersion: v1
kind: Pod
metadata:
  name: fio-test
  labels:
    role: fio-test
spec:
  containers:
    - name: fio
      image: dmonakhov/alpine-fio
      command: ["fio", "--name=random-writers-emptydir", "--filename=/test-volume/testfile", "--ioengine=libaio", "--iodepth=16", "--rw=randwrite", "--bs=512", "--direct=0", "--size=1G", "--numjobs=1", "--runtime=60s", "--group_reporting", "--fallocate=none", "--time_based", "--thread", "--invalidate=1", "--output-format=json"]
      volumeMounts:
        - name: test-volume
          mountPath: /test-volume
  restartPolicy: Never
  runtimeClassName: kata
  volumes:
    - name: test-volume
      emptyDir: {}
```

1. kubectl apply -f reproducer.yaml
2. Wait till the pod finishes
3. Check the content of `/var/log/pods/$namespace_$pod_name_$pod_uid/$container_name/$restart_number.log`

**Describe the results you received:**
The logs are empty.

**Describe the results you expected:**
Some log must be there, at least something. :-)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
[root@k8s cri-o]# /usr/bin/crio --version
crio version 1.18.3
Version:       1.18.3
GitCommit:     d6f1f19e0bd748fe2a461405bf6d0d3f3a5ec145
GitTreeState:  clean
BuildDate:     2020-08-14T18:38:20Z
GoVersion:     go1.14.6
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested on a single node kubernetes cluster, setup using kubeadm, using k8s 1.18 on a Fedora32 box.
