### ISSUE TITLE
high performance hook need to handle self-exit container

### ISSUE THREAD

**Issue by jianzzha** [cri-o/cri-o#4095]
**Description**

if a container that uses the high performance hook to set up CPUSLoadBalancing exits by itself, rather than using kubectl delete command to terminate it, then the CPUSLoadBalancing doesn't get a chance to recover. For example, using the follow yaml file to create a cyclictest pod that lives for "5s", 
```
apiVersion: v1 
kind: Pod 
metadata:
  name: cyclictest 
  annotations:
    cpu-load-balancing.crio.io: "true"
spec:
  runtimeClassName: high-performance
  restartPolicy: Never 
  containers:
  - name: container-perf-tools 
    image: quay.io/jianzzha/perf-tools
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "200Mi"
        cpu: "8"
    env:
    - name: tool
      value: "cyclictest"
    - name: DURATION
      value: "5s"
    - name: DISABLE_CPU_BALANCE
      value: "n"
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/cpu_dma_latency
      name: cstate
  volumes:
  - name: cstate
    hostPath:
      path: /dev/cpu_dma_latency
  nodeSelector:
    kubernetes.io/hostname: "worker0" 
```

After 5 second, the cyclictest completes and the pod state changes to "Completed". 

The cpu load balancing setting caused by the high-performance hooks is left behind and does not recover to its default value - it should revert back to 4655 after the pod is goes to "Completed" state. Deleting this "completed state" pod does not revert this setting.
```
/proc/sys/kernel/sched_domain/cpu0/domain0
4655
/proc/sys/kernel/sched_domain/cpu1/domain0
4655
/proc/sys/kernel/sched_domain/cpu10/domain0
4654
/proc/sys/kernel/sched_domain/cpu11/domain0
4654
/proc/sys/kernel/sched_domain/cpu12/domain0
4654
/proc/sys/kernel/sched_domain/cpu13/domain0
4655
/proc/sys/kernel/sched_domain/cpu14/domain0
4655
/proc/sys/kernel/sched_domain/cpu15/domain0
4655
/proc/sys/kernel/sched_domain/cpu16/domain0
4655
/proc/sys/kernel/sched_domain/cpu17/domain0
4655
/proc/sys/kernel/sched_domain/cpu18/domain0
4655
/proc/sys/kernel/sched_domain/cpu19/domain0
4655
/proc/sys/kernel/sched_domain/cpu2/domain0
4655
/proc/sys/kernel/sched_domain/cpu20/domain0
4655
/proc/sys/kernel/sched_domain/cpu21/domain0
4655
/proc/sys/kernel/sched_domain/cpu22/domain0
4655
/proc/sys/kernel/sched_domain/cpu23/domain0
4655
/proc/sys/kernel/sched_domain/cpu3/domain0
4655
/proc/sys/kernel/sched_domain/cpu4/domain0
4654
/proc/sys/kernel/sched_domain/cpu5/domain0
4654
/proc/sys/kernel/sched_domain/cpu6/domain0
4654
/proc/sys/kernel/sched_domain/cpu7/domain0
4654
/proc/sys/kernel/sched_domain/cpu8/domain0
4654
/proc/sys/kernel/sched_domain/cpu9/domain0
4654
```

**Steps to reproduce the issue:**
1. create a the cyclictest pog using above yaml or any yaml file that execution exits after certain time (for example centos with a sleep)
2. check the high performance hook set the cpu load balancing
3. after the pod is completed, check the cpu load balancing setting is same as in step2
4. kubectl delete the pod, check the cpu load balancing setting is same as in step2

**Describe the results you received:**
when the pod gets into "Completed" state, its cpu load balancing setting is not reverted

**Describe the results you expected:**
when the pod gets into "Completed" state, its cpu load balancing setting should be reverted

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
