### ISSUE TITLE
Drop ALL and add few caps doesn't work

### ISSUE THREAD

**Issue by mrunalp** [cri-o/cri-o#4922]
Creating a pod:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: shell
  name: shell
spec:
  containers:
  - image: busybox:1.24
    name: shell
    stdin: true
    tty: true
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
  dnsPolicy: ClusterFirst
  restartPolicy: Always
```

The running pod will include the default configured capabilities + NET_BIND_SERVICE when it should just be NET_BIND_SERVICE.
