### ISSUE TITLE
SSHD server failing in a container under CRIO (1.21) and Kubernetes (1.21), works fine under containerd

### ISSUE THREAD

**Issue by drtpotter** [cri-o/cri-o#5116]
Hi there,

I'm trying to use SSHD (OpenSSH_8.2p1 from Ubuntu focal) in a container under Kubernetes (1.21), CRI-O (1.21) and weave networking (2.8.1). If I start SSHD inside a container in debug mode and then try to initiate an SSH connection from anywhere, the connection attempt crashes SSHD with an unspecified error code 12, so nothing helpful unfortunately. The configuration of SSHD doesn't matter much, every connection attempt (even from localhost) crashes SSHD.

It might be tempting to dismiss this issue as SSHD-specific, however I have tried the exact same thing under the Containerd runtime (same container, same k8s, same weave-net etc) and it doesn't crash SSHD. So something CRI-O specific is clearly not working, perhaps it is related to what sort of packets are being fed to SSHD, possibly an issue with MTU packet sizes etc.

Any help on resolving this issue would be much appreciated! CRI-O integration with the nvidia-container-runtime is pretty good but I can't use CRI-O if this issue is going to persist.

Kind regards,
Toby

**Comment by saschagrunert** [comment]
Hey @drtpotter, can you share a container manifest being used for the test run?

**Comment by drtpotter** [comment]
Hi @saschagrunert, sure here is an example k8s manifest that reproduces the error.

apiVersion: v1
kind: ReplicationController
metadata:
  name: sshd-test
spec:
  replicas: 1
  selector:
    app: sshd-test
  template:
    metadata:
      name: sshd-test
      labels:
        app: sshd-test
    spec:
      containers:
      - name: sshd-test
        image: drtpotter/pelagos_compute:sshd_test
        ports:
        - containerPort: 22
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]

Once you have the pod started then login to it from two different terminals. In one terminal run sshd -ddd and in the other try to ssh to localhost. Here is the Dockerfile used to generate the container.

FROM jupyter/minimal-notebook:d990a62010ae

USER root

# Extra packages
RUN apt-get update
RUN apt-get -qq install openssh-server openssh-client nano

# Fix SSHD issue
RUN mkdir -p /var/run/sshd

# Clean?
RUN apt-get -qq clean

# Run sshd
CMD [ "/bin/bash", "-c", "sleep infinity" ]

**Comment by saschagrunert** [comment]
The first thing I noticed is that the sshd server requires `CAP_CHROOT`, which is disabled per default in CRI-O. It also looks like that the `UsePrivilegeSeparation` option has been deprecated in OpenSSH… Can you try to add the capability to your deployment to check if it works then?

```
  containers:
    …
    securityContext:
      capabilities:
        add:
          - sys_chroot
```

**Comment by drtpotter** [comment]
Hey @saschagrunert 

Yes, changing the manifest to

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: sshd-test
spec:
  replicas: 1
  selector:
    app: sshd-test
  template:
    metadata:
      name: sshd-test
      labels:
        app: sshd-test
    spec:
      containers:
      - name: sshd-test
        image: drtpotter/pelagos_compute:sshd_test
        securityContext:
          capabilities:
            add:
              - sys_chroot
        ports:
        - containerPort: 22
        command: ["/bin/bash"]
        args: ["-c", "sleep infinity"]
```
has resolved the issue. Thanks for spotting that.
