### ISSUE TITLE
userns-mode: cannot use uidmapping or gidmapping if not running as root

### ISSUE THREAD

**Issue by r10r** [cri-o/cri-o#5294]
Hi there,

i'm playing around with the userns-mode feature introduced in ad2ed3b79251ffa2f60f28ba4a975b24abc9d311

I noticed that is's only possible to use the `uidmapping` and `gidmapping` settings if the pod runs as root.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  annotations:
    io.kubernetes.cri-o.userns-mode: "private:uidmapping=0:100000:90000;gidmapping=0:100000:90000"
spec:
  nodeSelector:
    kubernetes.io/hostname: mynode
  securityContext:
    runAsUser: 0
  containers:
  - name: busybox
    image: docker.io/library/busybox:latest
    command:
      - sleep
      - "3600"
```

If I remove `spec.securityContext.runAsUser: 0` I'll get the following error:

> cannot use uidmapping or gidmapping if not running as root

But if possible I want to run the containers as non-root.
So out of curiosity I disabled the user check and recompiled cri-o - and it works perfectly fine without it.

https://github.com/cri-o/cri-o/blob/7bad536afb617cf0b343b516c22cc1a288e51520/server/sandbox_run_linux.go#L95-L100

@giuseppe Is there a reason for this limitation ?

**Environment**

* **uname**: 5.10.43-1-lts
* **cat /etc/os-release**: NAME="Arch Linux"
* **crio --version**: v1.20.3 (modified with the above check disabled)
* **runc --version**: v1.0.2-0-g52b36a2d
* **kubelet --version**: v1.20.7

**Comment by r10r** [comment]
The discussion may contribute to the userns-mode documentation issue #5030

**Comment by haircommander** [comment]
@giuseppe WDYT

**Comment by giuseppe** [comment]
> @giuseppe Is there a reason for this limitation ?

the reason for this limitation is to avoid an user could map root (or another privileged user) on the host to a different ID in the container.  That would circumvent all the limitations in place (like the OpenShift SCCs) for the UID used to run the container.

It is allowed only for root, since if you are already running as root there is nothing to gain from this feature.

**Comment by r10r** [comment]
@giuseppe Thanks for the response.

Since I'm not an OpenShift user I'm not familiar with the [OpenShift Security Context Contraints](https://docs.openshift.com/container-platform/4.8/authentication/managing-security-context-constraints.html).

Shouldn't `/etc/subuid` and `/etc/subgid` be used  to check if the pods id mappings are valid ?

I would expect that the following works:

**/etc/subuid**

```
3000:200000:100000
```

**/etc/subgid**

```
3000:200000:100000
```


```yaml
apiVersion: v1
kind: Pod
metadata:
  name: userns-pod3
  annotations:
    io.kubernetes.cri-o.userns-mode: "private:uidmapping=0:200000:100;gidmapping=0:200000:100"
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-cluster9-controller
  securityContext:
    runAsUser: 3000
  containers:
  - name: busybox
    image: docker.io/library/busybox:latest
    command:
      - sleep
      - "3600"
```
