### ISSUE TITLE
Incorrect mount propagation information in container status  

### ISSUE THREAD

**Issue by harche** [cri-o/cri-o#5916]
### What happened?

When container status is requested (e.g. by [crictl](https://github.com/kubernetes-sigs/cri-tools/blob/master/cmd/crictl/container.go#L411)), the mount propagation related information is not presented correctly. 

If we run a container which uses mount propagation, e.g.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: proapagate-pod
spec:
  volumes:
  - name: host
    hostPath:
      path: /
  containers:
    - name: propagate-pod
      image: nginx
      securityContext:
        privileged: true
      volumeMounts:
       - name: host
         mountPath: /host
         mountPropagation: HostToContainer
```
 
ContainerStatus returned by crio for such container looks like, 

```
    "mounts": [
      {
        "containerPath": "/host",
        "hostPath": "/",
        "propagation": "PROPAGATION_PRIVATE",
        "readonly": false,
        "selinuxRelabel": false
      },
 ```

This is happening because crio never fills the [Propagation](https://github.com/cri-o/cri-o/blob/main/vendor/k8s.io/cri-api/pkg/apis/runtime/v1/api.pb.go#L520) field while [returning the container status](https://github.com/cri-o/cri-o/blob/main/server/container_status.go#L44). Hence it defaults to `PROPAGATION_PRIVATE`. 

For what it's worth, if you run the same container with containerd, the returned value from the container status is correct.

```
    "mounts": [
      {
        "containerPath": "/host",
        "hostPath": "/",
        "propagation": "PROPAGATION_HOST_TO_CONTAINER",
        "readonly": false,
        "selinuxRelabel": false
      },
```

### What did you expect to happen?

CRIO to return correct value for mount propagation while returning container status

### How can we reproduce it (as minimally and precisely as possible)?

Run the container that uses mount propagation, and the inspect the container using `crictl` 

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl --version
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>
