### ISSUE TITLE
highperformance irq balancing support causes the `/etc/sysconfig/irqbalance` to slowly grow unbounded

### ISSUE THREAD

**Issue by fromanirh** [cri-o/cri-o#6086]
### What happened?

The highperformance hooks can update the irqbalance configuration file to adjust the current banned cpu list,
depending on pod annotations. This is done to make sure that guaranteed pods that declare they don't want to have IRQ
processing on the CPUs they're assigned to, gets that.
    
When the update is done in-place, so likely most of the time,  a stray '\n' is added on _every_ update. The single character
always adds up, creating a unbounded growth of the configuration file.
    
In practical terms, this is likely not really too bad, because we will need to get in the ballpark of thousands updates before the file size starts becoming concerning.

### What did you expect to happen?

obviously the file size can change (and grow) depending on the actual CPU ban list, but the rewrites should not cause unlimited '\n' to be added to the file

### How can we reproduce it (as minimally and precisely as possible)?

1. setup a cluster >= OCP 4.11 (for practical purposes, but the bug is likely here since the introduction of irq handling)
2. apply a performance profile like this minimal example[1], to get the runtimeclass deployed which enables the feature
3. create/delete pods like the example[2], notice (`oc debug node/...`) after each pod creation a `\n` is added to `/etc/sysconfig/irqbalance`

[1]
```
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: perfprof
spec:
  cpu:
      isolated: "1-3"
      reserved: "0"
  nodeSelector:
    node-role.kubernetes.io/worker: ""
```

[2]
```
apiVersion: v1
kind: Pod
metadata:
  generateName: numalign-pod-
  annotations:
    irq-load-balancing.crio.io: "disable"
    cpu-quota.crio.io: "disable"
spec:
  runtimeClassName: "performance-perfprof"
  containers:
  - name: numalign
    image: quay.io/fromani/numalign
    imagePullPolicy: IfNotPresent
    command: ["/usr/local/bin/numalign"]
    env:
      - name: NUMALIGN_SLEEP_HOURS
        value: "127"
    resources:
      limits:
        cpu: 1
        memory: 200Mi
      requests:
        cpu: 1
        memory: 200Mi

```

### Anything else we need to know?

this bug is likely present since the first addition of the high performance hooks

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.24.1-11.rhaos4.11.gitb0d2ef3.el8
Version:          1.24.1-11.rhaos4.11.gitb0d2ef3.el8
GoVersion:        go1.18.1
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        exclude_graphdriver_devicemapper, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl --version
Client Version: 4.10.9
Server Version: 4.11.0-0.nightly-2022-07-19-104004
Kubernetes Version: v1.24.0+9546431
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
physical/bare metal
</details>
