### ISSUE TITLE
Startup probe fails on Crio-1.24

### ISSUE THREAD

**Issue by rkojedzinszky** [cri-o/cri-o#6184]
### What happened?

Upgraded cri from cri-o-1.23 to cri-o-1.24, and pods having startupProbes of exec type fails to get ready.

### What did you expect to happen?

A seamless upgrade

### How can we reproduce it (as minimally and precisely as possible)?

Have a k8s deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - image: ghcr.io/kubernetize/unbound:3.16.2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - dig
            - '@127.0.0.1'
            - .
            - ns
            - +tcp
        name: unbound
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
          runAsNonRoot: true
        startupProbe:
          exec:
            command:
            - nslookup
            - -type=soa
            - google.com
            - 127.0.0.1
```

### Anything else we need to know?

Kubelet reports this:

```
kubelet[615]: E0829 16:06:43.000635     615 remote_runtime.go:711] "ExecSync cmd from runtime service failed" err="rpc error: code = Unknown desc = command error: EOF, stdout: , stderr: , exit code -1" containerID="24e4a26ed30e7ebdd165f59f294bbe28a4b53a2b79dbcf7dbaa80144ec4cc1fd" cmd=[nslookup -type=soa <hidden-domain>  127.0.0.1]
```

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.24.2
Version:          1.24.2
GitCommit:        f4d632b8f61915e51f70784a5b2dab76a5af05b4
GitTreeState:     clean
BuildDate:        2022-08-29T12:40:58Z
GoVersion:        go1.18.5
Compiler:         gc
Platform:         linux/arm64
Linkmode:         dynamic
BuildTags:        apparmor, exclude_graphdriver_devicemapper, containers_image_openpgp, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:47:37Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/arm64"}
```

</details>

### OS version

<details>

```console
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# uname -a
Linux k8s-node01 5.15.63 #10 SMP Thu Aug 25 11:07:49 UTC 2022 aarch64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Bare metal.
</details>
