### ISSUE TITLE
Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load context deadline exceeded: error reserving ctr name

### ISSUE THREAD

**Issue by vjvel** [cri-o/cri-o#6185]
### What happened?

We are getting the below error while mount the pvc volume for the minio. This pvc has 1.7TB and 900GB of data. it not mounting to the pod and container is failed to start with below error.

```
Normal Pulled 47m (x77 over 3h35m) kubelet Container image "minio/minio:RELEASE.2021-10-06T23-36-31Z" already present on machine
Warning Failed 5m22s (x53 over 3h33m) kubelet Error: context deadline exceeded
Warning Failed 53s (x36 over 149m) kubelet (combined from similar events): Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: context deadline exceeded: error reserving ctr name k8s_minio_data-analytics-prod-pool-0-3_oci-prod-data-analytics_8dec4302-e6b4-4874-9a60-ea305b96347f_0 for id 8424e8fdc1a42daec5810b43a8baf7a9a80f7835a843fc104fe9f621a14983cb: name is reserved
```

### What did you expect to happen?

It should mount the pvc to the pod , not timeout should come

### How can we reproduce it (as minimally and precisely as possible)?

minio with huge data has this issue.

### CRI-O and Kubernetes version

crio version 1.21.6-79.el7
Version:       1.21.6-79.el7
Linkmode:      dynamic

### OS version

RHEL 7.9

### Additional environment details (AWS, VirtualBox, physical, etc.)

Oracle cloud infrastructure 

1.21 OKE cluster

**Comment by haircommander** [comment]
So something to note about this error: you will get it and it will populate the events api, but eventually the container will successfully be created. Kubelet is retrying because cri-o is taking longer than expected to label that directory. A workaround exists if you don't want to wait every time:

if you give the pod `io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel` (as well as the workload or runtime it's running in
```
allowed_annotations = ["io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel"]
```

the relabel will be skipped if the top level of the PVC is correctly labeled. You can then either prelabel the directory, or pay the up front cost of cri-o relabeling the directory once, and subsequent restarts of the same container will not incur the same cost.

**Comment by vjvel** [comment]
@haircommander 

Added the annotation but still getting the same error. How can we prelabel the directory ?   added this annoations in the pod 
`io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: true`

``` 
Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               5m59s                default-scheduler        Successfully assigned oci-prod-data-analytics/task-pv-pod to 10.0.94.164
  Normal   SuccessfulAttachVolume  5m33s                attachdetach-controller  AttachVolume.Attach succeeded for volume "csi-924a0d92-2b67-4ead-b5f7-52496b87fb11"
  Normal   Pulled                  5m15s                kubelet                  Successfully pulled image "nginx" in 10.569104618s
  Warning  Failed                  3m15s                kubelet                  Error: context deadline exceeded
  Normal   Pulled                  3m11s                kubelet                  Successfully pulled image "nginx" in 3.416629966s
  Warning  Failed                  71s                  kubelet                  Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: context deadline exceeded: error reserving ctr name k8s_test-nginx_task-pv-pod_oci-prod-data-analytics_9e5f41be-13d2-4d45-817c-0812f6cb0462_0 for id bda7db4c923f9635f1b7338ec996f63b28599833de1e7b0568615432e8f5473e: name is reserved
  Normal   Pulling                 70s (x3 over 5m25s)  kubelet                  Pulling image "nginx"
  Normal   Pulled                  66s                  kubelet                  Successfully pulled image "nginx" in 3.399097935s
```

**Comment by saschagrunert** [comment]
Refers to https://github.com/kubernetes/kubernetes/issues/112105

**Comment by haircommander** [comment]
you can use [securityContext](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#assign-selinux-labels-to-a-container) to choose the label for the pod:

```
...
securityContext:
  seLinuxOptions:
    level: "s0:c123,c456"
    role: "object_r"
    user: "system_u"
    type: "container_file_t"
```

then the resulting label for the PVC will be `system_u:object_r:container_file_t:s0:c123,c456` which you can prelabel with `chcon`

**Comment by haircommander** [comment]
@vjvel did you figure this out?

**Comment by AdmiralNemo** [comment]
I think I'm having this problem as well. I have a pod with a PVC with about 1.5 million files that hangs for 5+ minutes in ContainerCreating status.  I've tried adding the `io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel` label to the pod:

```yaml
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    metadata:
      annotations:
        io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: 'true'
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seLinuxOptions:
          level: s0:c375,c725
          role: object_r
          type: container_file_t
          user: system_u
```

and added this to `crio.conf`:

```toml
[crio.runtime]
default_runtime = "main"

[crio.runtime.runtimes.main]
allowed_annotations = ["io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel"]
```

This resulted in the pod not being able to start at all:

```
time="2022-11-19 01:08:04.051466558Z" level=error msg="Container creation error: time=\"2022-11-19T01:08:04Z\" level=error msg=\"runc create failed: unable to start container process: error during container init: write /proc/self/attr/keycreate: permission denied\"\n" id=4f2a18a9-d05a-4e38-b40b-837399395d08 name=/runtime.v1alpha2.RuntimeService/CreateContainer
```

I copied the SELinux label from the mount point of the volume when it was running.  Removing `seLinuxOptions` lets the container start, but it still takes over 5 minutes, and it comes up with different category numbers in the label.

**Comment by vjvel** [comment]
we are completely disabled the selinux on the worker nodes to avoid this issue.

**Comment by AdmiralNemo** [comment]
I was finally able to get the `TrySkipVolumeSELinuxLabel` annotation to work.  The key was simply setting `seLinuxOptions.level` instead all the label fields.  Here's what I ended up with:

```yaml
apiVersion: apps/v1
kind: StatefulSet
spec:
  template:
    metadata:
      annotations:
        io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel: 'true'
    spec:
      containers:
      - securityContext:
          seLinuxOptions:
            level: s0:c525,c600
```

I also had to add this to `/etc/crio/crio.conf`:

```toml
[crio.runtime.runtimes.runc]
allowed_annotations = ["io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel"]
```

Now my container that used to take 5+ minutes to start comes up instantly!
