### ISSUE TITLE
Configuration files cannot remove implicit metacopy=on from crio.storage_option

### ISSUE THREAD

**Issue by dilyanpalauzov** [cri-o/cri-o#6191]
### What happened?

On my system I have no file called `storage.conf`, so only defailts are implied. The file /etc/crio/crio.conf contains:
```toml
[crio]
# Storage driver used to manage the storage of images and containers. Please
# refer to containers-storage.conf(5) to see all available storage drivers.
# storage_driver = "overlay"

# List to pass options to the storage driver. Please refer to
# containers-storage.conf(5) to see all available storage options.
# storage_option = [
#       "overlay.mountopt=nodev,metacopy=on",
# ]
```
I guess that are the default values, prefixed by `#` to imply comment.

Moreover I have /etc/crio/crio.conf.d/10-crio.conf:
```toml
[crio.runtime]
default_runtime="crun"
# cgroup_manager = "cgroupfs"
[crio.runtime.runtimes.crun]
runtime_path = "/usr/local/bin/crun"
```
and /etc/crio/crio.conf.d/01-userns-workload.conf:
```toml
[crio]

#metacopy=on is deleted
#      "overlay.mountopt=nodev",
storage_option = [
       "overlay.mountopt=nodev",
       "overlay.mount_program=/usr/bin/fuse-overlayfs"
]


[crio.runtime.workloads.userns]
activation_annotation = "io.kubernetes.cri-o.userns-mode"
allowed_annotations = ["io.kubernetes.cri-o.userns-mode"]
```

### What did you expect to happen?

I exect that crio config does not include `metacopy=on` in crio.storage_option.  But `crio config` prints on stderr:

```
INFO[2022-08-31 14:37:14.312648708+03:00] Starting CRI-O, version: 1.25.0, git: f36bc747908c1609efcce490e0d16c785f5372c0(clean) 
INFO Using default capabilities: CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_FSETID, CAP_FOWNER, CAP_SETGID, CAP_SETUID, CAP_SETPCAP, CAP_NET_BIND_SERVICE, CAP_KILL 
FATA template: config:428:29: executing "config" at <$workload_config.Resources.CPUSet>: nil pointer evaluating *config.Resources.CPUSet
```
and on stdout (incomplete output):
```
# List to pass options to the storage driver. Please refer to
# containers-storage.conf(5) to see all available storage options.
storage_option = [
        "overlay.mountopt=nodev,metacopy=on",
        "overlay.mountopt=nodev",
        "overlay.mount_program=/usr/bin/fuse-overlayfs",
]
```

So the default, implicit `metacopy=on` does not come from any configuration file, but at the same time cannot be removed.

Concirnig the FATA-message on stderr I filled https://github.com/cri-o/cri-o/issues/6188.

I expect that in the above cnofiguration `crio config` does not print `metacopy=on`  in crio.storage_option.

### How can we reproduce it (as minimally and precisely as possible)?

Not applicable.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.25.0
Version:        1.25.0
GitCommit:      f36bc747908c1609efcce490e0d16c785f5372c0
GitCommitDate:  2022-08-30T09:57:07Z
GitTreeState:   clean
BuildDate:      2022-08-30T16:53:57Z
GoVersion:      go1.18.5
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  containers_image_ostree_stub
  exclude_graphdriver_btrfs
  btrfs_noversion
  containers_image_openpgp
  seccomp
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:     

```

```console
$ kubectl --version
irrelevant, but the precise output is:

error: unknown flag: --version
See 'kubectl --help' for usage.
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
$ uname -a
Linux d 5.19.4-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Aug 25 17:42:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

</details>


### Additional environment details (AWS, VirtualBox, physical, etc.)

None
