### ISSUE TITLE
No metrics reported from CRI-O: Unable to account working set stats: total_inactive_file > memory usage

### ISSUE THREAD

**Issue by 0xC0ncord** [cri-o/cri-o#6747]
### What happened?

On a 3-node cluster deployed with kubeadm and using CRI-O, I am seeing a situation where after some amount of workload is allocated to a node, the node stops reporting any metrics (CPU/memory usage is 0% or `<unknown>` in `kubectl top nodes`). In the system journal for CRI-O, I can see these warnings being emitted every second or so on the affected nodes:
```
Mar 18 16:09:13 ram.fuwafuwatime.moe crio[72618]: time="2023-03-18 16:09:13.067279194-04:00" level=warning msg="Unable to account working set stats: total_inactive_file (3827683328) > memory usage (3233787904)"
Mar 18 16:09:18 ram.fuwafuwatime.moe crio[72618]: time="2023-03-18 16:09:18.919610520-04:00" level=warning msg="Unable to account working set stats: total_inactive_file (3827683328) > memory usage (3233787904)"
Mar 18 16:09:24 ram.fuwafuwatime.moe crio[72618]: time="2023-03-18 16:09:24.932763766-04:00" level=warning msg="Unable to account working set stats: total_inactive_file (3827683328) > memory usage (3233746944)"
Mar 18 16:09:31 ram.fuwafuwatime.moe crio[72618]: time="2023-03-18 16:09:31.687808594-04:00" level=warning msg="Unable to account working set stats: total_inactive_file (3827683328) > memory usage (3233759232)"
```

If I execute `kubectl top nodes` on the cluster, I get this output:
```
NAME                         CPU(cores)   CPU%        MEMORY(bytes)   MEMORY%     
frederica.fuwafuwatime.moe   1867m        23%         17545Mi         55%         
ram.fuwafuwatime.moe         <unknown>    <unknown>   <unknown>       <unknown>   
rem.fuwafuwatime.moe         <unknown>    <unknown>   <unknown>       <unknown>   
```

And in `k9s`, the pods running on these nodes report no CPU/memory usage (0%):
![image](https://user-images.githubusercontent.com/8011001/226431622-f306fb9f-5628-499f-adeb-783945429d7c.png)

### What did you expect to happen?

Metrics should be visible from these nodes, regardless of workload.

### How can we reproduce it (as minimally and precisely as possible)?

This is what I have done:

1. Deploy a 3-node kubernetes cluster using `kubeadm` and CRI-O (one "master" node, 2 worker nodes, all 3 running control plane pods).
2. Deploy Calico.
3. Deploy `metrics-server`.
4. Run some workloads on the cluster.

It seems most of the time this issue occurs on nodes that have at least (about) 50% memory utilization, but I haven't found a reliable reproducer yet.

### Anything else we need to know?

SELinux is enabled on the hosts in this cluster using [Gentoo's fork](https://gitweb.gentoo.org/proj/hardened-refpolicy.git/) of [refpolicy](https://github.com/SELinuxProject/refpolicy.git), but I have been able to reproduce this issue even when SELinux is in permissive mode.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.26.0
Version:        1.26.0
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2022-12-25T22:53:52Z
GoVersion:      go1.19.4
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  containers_image_ostree_stub
  exclude_graphdriver_btrfs
  btrfs_noversion
  containers_image_openpgp
  seccomp
  selinux
LDFlags:          -s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=2022-12-25T22:53:52Z 
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:     
  
```

```console
$ kubectl version -o yaml
clientVersion:
  buildDate: "2023-03-10T00:50:26Z"
  compiler: gc
  gitCommit: fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b
  gitTreeState: archive
  gitVersion: v1.26.2
  goVersion: go1.20.1
  major: "1"
  minor: "26"
  platform: linux/amd64
kustomizeVersion: v4.5.7
serverVersion:
  buildDate: "2023-02-22T13:32:22Z"
  compiler: gc
  gitCommit: fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b
  gitTreeState: clean
  gitVersion: v1.26.2
  goVersion: go1.19.6
  major: "1"
  minor: "26"
  platform: linux/amd64

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.13"
$ uname -a
Linux ram.fuwafuwatime.moe 6.1.15-gentoo-hardened1 #1 SMP Tue Mar  7 19:50:39 EST 2023 x86_64 AMD EPYC 7313 16-Core Processor AuthenticAMD GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Bare metal nodes
</details>

**Comment by haircommander** [comment]
did you enable the `PodAndContainerStatsFromCRI` feature gate? (currently in alpha)

**Comment by haircommander** [comment]
I think at least you should restart cri-o but probably reboot the node is the best way to make sure the change takes effect

**Comment by 0xC0ncord** [comment]
OK, I've rebooted each node in the cluster with the feature gate enabled, however I still see the same behavior. The nodes come up fine and report metrics at first, but as soon as I uncordon them after draining and rebooting, they stop reporting metrics after running workloads for about 10 minutes or so.

**Comment by haircommander** [comment]
could you post the crio logs

**Comment by 0xC0ncord** [comment]
Here's the complete CRI-O log from the system journal on one of the afflicted nodes since it was rebooted this morning: [crio.log](https://github.com/cri-o/cri-o/files/11044567/crio.log)

**Comment by 0xC0ncord** [comment]
I'm still seeing the same warning from CRI-O despite having worked around metrics reporting by increasing the timeout from `metrics-server` to a really high value.

That being said, I am still on CRI-O 1.26.0, hoping to be able to test again with 1.27.0 when it becomes available in Gentoo.

**Comment by haircommander** [comment]
sorry for the delay here. currently, CRI stats has some issues that need working through. An option for now is to use cadvisor stats provider in the kubelet while we work through the issues

**Comment by zestysoft** [comment]
fwiw, after updating this on all my nodes, the only ones that exhibited this behavior were the ones running Ubuntu 22.04 LTS.  20.04 on ARM and AMD worked fine, as did my Fedora 37 node (vm running on apple silicon).  All of my nodes should be fairly similar in how they were set up -- bare minimum to run kubernetes.

**Comment by haircommander** [comment]
can you post kubelet config and crio config from both node types?

**Comment by zestysoft** [comment]
Sure --  the files are identical for both node types:

sudo cat /var/lib/kubelet/config.yaml:
```
apiVersion: kubelet.config.k8s.io/v1beta1
authentication:
  anonymous:
    enabled: false
  webhook:
    cacheTTL: 0s
    enabled: true
  x509:
    clientCAFile: /etc/kubernetes/pki/ca.crt
authorization:
  mode: Webhook
  webhook:
    cacheAuthorizedTTL: 0s
    cacheUnauthorizedTTL: 0s
cgroupDriver: systemd
clusterDNS:
- 10.96.0.10
clusterDomain: cluster.local
cpuManagerReconcilePeriod: 0s
evictionPressureTransitionPeriod: 0s
fileCheckFrequency: 0s
healthzBindAddress: 127.0.0.1
healthzPort: 10248
httpCheckFrequency: 0s
imageMinimumGCAge: 0s
kind: KubeletConfiguration
logging:
  flushFrequency: 0
  options:
    json:
      infoBufferSize: "0"
  verbosity: 0
memorySwap: {}
nodeStatusReportFrequency: 0s
nodeStatusUpdateFrequency: 0s
resolvConf: /run/systemd/resolve/resolv.conf
rotateCertificates: true
runtimeRequestTimeout: 0s
shutdownGracePeriod: 0s
shutdownGracePeriodCriticalPods: 0s
staticPodPath: /etc/kubernetes/manifests
streamingConnectionIdleTimeout: 0s
syncFrequency: 0s
volumeStatsAggPeriod: 0s
```

cat /etc/crio/crio.conf|grep -Ev "^(#.*|\s*)$":
```
[crio]
[crio.api]
[crio.runtime]
[crio.image]
[crio.network]
[crio.metrics]
[crio.tracing]
[crio.stats]
```

cat /etc/crio/crio.conf.d/01-crio-runc.conf:
```
[crio.runtime.runtimes.runc]
runtime_path = "/usr/lib/cri-o-runc/sbin/runc"
runtime_type = "oci"
runtime_root = "/run/runc"
```

cat /var/lib/kubelet/kubeadm-flags.env:
```
KUBELET_KUBEADM_ARGS="--container-runtime=remote --container-runtime-endpoint=unix:///run/crio/crio.sock --feature-gates='SeccompDefault=true'"
```

The only difference is this file where I disabled the warnings by changing the log level
cat /etc/default/crio:
```
# /etc/default/crio
CRIO_CONFIG_OPTIONS="--log-level=error"
# use "--enable-metrics" and "--metrics-port value"
#CRIO_METRICS_OPTIONS="--enable-metrics"

#CRIO_NETWORK_OPTIONS=
#CRIO_STORAGE_OPTIONS=
```

vs
cat /etc/default/crio:
```
# /etc/default/crio

# use "--enable-metrics" and "--metrics-port value"
#CRIO_METRICS_OPTIONS="--enable-metrics"

#CRIO_NETWORK_OPTIONS=
#CRIO_STORAGE_OPTIONS=
```
