### ISSUE TITLE
userns: Failed to create pod sandbox: invalid argument

### ISSUE THREAD

**Issue by Raniz85** [cri-o/cri-o#6792]
### What happened?

I've enabled userns by following https://github.com/cri-o/cri-o/blob/main/tutorials/userns.md#1230-and-beyond but when I start a pod with `io.kubernetes.cri-o.userns-mode: auto` I get the following error:

```
  Warning  FailedCreatePodSandBox  1s    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to mount container k8s_POD_userns_default_3f490b8b-410b-42d7-ad47-0ca7f8d43997_0 in pod sandbox k8s_userns_default_3f490b8b-410b-42d7-ad47-0ca7f8d43997_0(a3332a7bc0d0b17124c0f86900ea572a5c066dfea2f9e1b6020e4337f75262c8): create mapped mount for "/var/lib/containers/storage/overlay" on "/var/lib/containers/storage/overlay/1f46a9777ed11fc6c65989778e864bfbe4ec71befcab657b00be92e4e001b61d/mapped/0": invalid argument
```

### What did you expect to happen?

The pod should start

### How can we reproduce it (as minimally and precisely as possible)?

Install OKD using CRC, enable userns by applying the following MC:

<details>

```yaml
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 05-userns
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - path: /etc/subuid
        mode: 0644
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64,Y29yZToxMDAwMDA6NjU1MzYKY29udGFpbmVyczoyMDAwMDA6MjY4NDM1NDU2Cg==
      - path: /etc/subgid
        mode: 0644
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64,Y29yZToxMDAwMDA6NjU1MzYKY29udGFpbmVyczoyMDAwMDA6MjY4NDM1NDU2Cg==
      - path: /etc/crio/crio.conf.d/05-userns.conf
        mode: 0644
        overwrite: true
        contents:
          source: data:text/plain;charset=utf-8;base64,W2NyaW8ucnVudGltZS53b3JrbG9hZHMudXNlcm5zXQphY3RpdmF0aW9uX2Fubm90YXRpb24gPSAiaW8ua3ViZXJuZXRlcy5jcmktby51c2VybnMtbW9kZSIKYWxsb3dlZF9hbm5vdGF0aW9ucyA9IFsiaW8ua3ViZXJuZXRlcy5jcmktby51c2VybnMtbW9kZSJdCg==
```

</details>

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.25.1
Version:        1.25.1
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
GoVersion:      go1.18.6
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  rpm_crashtraceback
  seccomp
  selinux
LDFlags:           -X github.com/cri-o/cri-o/version=1.25.1 -B 0x9a53a233b290a744a509e0e1d50c578d82581146 -compressdwarf=false -linkmode=external -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -Wl,-dT,/builddir/build/BUILD/cri-o-1.25.1/.package_note-cri-o-1.25.1-None.fc36.x86_64.ld '
SeccompEnabled:   true
AppArmorEnabled:  false
Dependencies:     
  
```

```console
$ oc version
Client Version: 4.12.0-0.okd-2023-02-18-033438
Kustomize Version: v4.5.7
Server Version: 4.12.0-0.okd-2023-02-18-033438
Kubernetes Version: v1.25.0-2653+a34b9e9499e6c3-dirty
```

</details>

### OS version

<details>

```console
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="37.20230110.3.1 (CoreOS)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora CoreOS 37.20230110.3.1"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='37.20230110.3.1'
```

```console
$ uname -a
Linux crc-dp64w-master-0 6.0.18-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 7 17:10:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

```console
$ crc status
CRC VM:          Running
OpenShift:       Running (v4.12.0-0.okd-2023-02-18-033438)
RAM Usage:       5.719GB of 20.97GB
Disk Usage:      17.75GB of 42.34GB (Inside the CRC VM)
Cache Usage:     36.37GB
Cache Directory: /home/raniz/.crc/cache
```

</details>
