### ISSUE TITLE
cri-o can lose track of finished init containers

### ISSUE THREAD

**Issue by PaulFurtado** [cri-o/cri-o#7004]
### What happened?

The crio service was restarted and the finished state for an init container was lost, which led cri-o to claim that it was now running again. This does not happen for all pods, we restarted crio on 4,000 nodes and 5-6 of them exhibited this issue. The init containers were not recent init containers, they had finished days prior to the restart.

Due to this, cri-o then could not later terminate the pod because it thought the init container was running. Attempting to inspect the container would hang, etc.

In this output you can see the containerStatuses and initContainerStatuses for a pod. It shows all containers in the pod are running, one of the init containers is completed, and one of the init containers is in the running state. Prior to the cri-o restart, the init container was in the finished state.
<details>

```yaml

 containerStatuses:
  - containerID: cri-o://071e6fcb6a2a1cb5e94c96df783e2f36268de75c1f21dacafa14b8d84f0453ed
    image: docker.hubteam.com/zookeeper-docker/zookeeper-haproxy:345
    imageID: c8ec252e0d08b382bcd7927e890aceeae31c42db32b014fa33467ba9bf5c0808
    lastState: {}
    name: adminserver-haproxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-16T22:44:52Z"
  - containerID: cri-o://c58e512b026ea957577d4f609a4366c5628233329a07382542c31b3ab311791d
    image: docker.hubteam.com/zookeeper-docker/zookeeper-3.6.3:359
    imageID: dd51cf96dff7182c56f947f0302efbe189b3f5a77e12e5f493564d149b79c4d5
    lastState: {}
    name: zookeeper
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-16T22:44:46Z"
  - containerID: cri-o://04345b9ea0c8206454ec98b65e1cf58dc8aa4694ec4d2cf1dd255b4c09eae297
    image: docker.hubteam.com/zookeeper-docker/zookeeper-backups-3.6.3:344
    imageID: ae4206d208af5ec4650455895dc3a489debcfcbcac8adc5bd763e15135b5db3a
    lastState: {}
    name: zookeeper-backups
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-16T22:44:48Z"
  - containerID: cri-o://58efc8b66335c3f6ea251c41e7435e5fe5f5d3c79610cee0d5d3d068e12755df
    image: docker.hubteam.com/dockerbaseimages/centos-8-base:480
    imageID: 1aa2ce41b03a7fb75d4a8d0af615db6a6608e18fc6d3cb76e6e3bf1e0b97093c
    lastState: {}
    name: zookeeper-cert-rotation
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-16T22:44:54Z"
  - containerID: cri-o://afeb279bcea07f82cbad5e1ec81bc83de0cf5bf9cb3fe3dfb06f423f94b27b2e
    image: docker.hubteam.com/zookeeper-docker/zookeeper-metrics-3.6.3:344
    imageID: becd9def5c304a2d89b2042b20991dd81481b2ac4375edbbc5ea7599be49a938
    lastState: {}
    name: zookeeper-metrics
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-16T22:44:50Z"
  hostIP: 172.18.68.207
  initContainerStatuses:
  - containerID: cri-o://1422de00af70d9890a1888e97a274ae3258341d4e2a420cf6750709b084762cc
    image: docker.hubteam.com/zookeeper-docker/zookeeper-backup-restore-3.6.3:344
    imageID: 6f4eb61421e2ebb367817b077ed7d24f9e8701783848d6cfc3b101076b83d311
    lastState: {}
    name: zookeeper-backup-restore
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: cri-o://1422de00af70d9890a1888e97a274ae3258341d4e2a420cf6750709b084762cc
        exitCode: 0
        finishedAt: "2023-05-16T22:44:40Z"
        reason: Completed
        startedAt: "2023-05-16T22:44:40Z"
  - containerID: cri-o://ccdc8536e34e41f15db548dc75d6fd336a5a94347abe39aa4f83f9846c80c00f
    image: docker.hubteam.com/dockerbaseimages/centos-8-base:480
    imageID: 1aa2ce41b03a7fb75d4a8d0af615db6a6608e18fc6d3cb76e6e3bf1e0b97093c
    lastState: {}
    name: zookeeper-cert-init
    ready: false
    restartCount: 0
    state:
      running:
        startedAt: "2023-05-16T22:44:42Z"
```
</details>

Excerpt from `/var/lib/containers/storage/overlay-containers/ac0ef2d30916d89a4f5c551e07389067b3550d65a5cb4a41edec14a7d2224ef1/userdata/state.json`:
```json
{"created":"2023-05-16T22:44:42.000597071Z","started":"2023-05-16T22:44:42.90278941Z","finished":"2023-05-16T22:44:42.905368517Z","exitCode":0,"initPid":3265212,"initStartTime":"124174355"}
```
Forgive me for incomplete file, I was copy-pasting from terminal and slack history, but what I intended to show was that the state.json file had the accurate finished time in it and yet cri-o didn't realize that upon restart.

### What did you expect to happen?

finished container state should be restored upon cri-o restart

### How can we reproduce it (as minimally and precisely as possible)?

It is intermittent, so I don't know. However, maybe your test suite should be restarting crio and verifying container states to detect flakiness like this.

### CRI-O and Kubernetes version

<details>

```console
# crio --version
crio version 1.23.4
Version:          1.23.4
GitCommit:        a6a1e6ebf4c4baca7ca7d57f069a4e0cd89056cd
GitTreeState:     dirty
BuildDate:        1980-01-01T00:00:00Z
GoVersion:        go1.17.4
Compiler:         gc
Platform:         linux/amd64
Linkmode:         static
BuildTags:        apparmor, exclude_graphdriver_devicemapper, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
 QA - iad03  [root@ip-172-18-63-2
```

```console
# kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.16",
    "gitCommit": "60e5135f758b6e43d0523b3277e8d34b4ab3801f",
    "gitTreeState": "archive",
    "buildDate": "2023-05-17T15:49:52Z",
    "goVersion": "go1.19.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "serverVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.16",
    "gitCommit": "60e5135f758b6e43d0523b3277e8d34b4ab3801f",
    "gitTreeState": "archive",
    "buildDate": "2023-05-17T15:49:52Z",
    "goVersion": "go1.19.5",
    "compiler": "gc",
    "platform": "linux/arm64"
  }
}
```

</details>

### OS version

<details>

```console
# cat /etc/os-release 
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

# uname -a
Linux ip-172-18-63-221 5.15.86-hs36.el8.x86_64 #1 SMP Thu Mar 2 01:02:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
- AWS (non-EKS)
</details>
