### ISSUE TITLE
Restored pod does not executes the command

### ISSUE THREAD

**Issue by varungup90** [cri-o/cri-o#7050]
### What happened?

I create a simple pod with `command: ['sh', '-c', "while :; do echo '.'; sleep 5 ; done"]`, checkpoint and restore using this [tutorial](https://martinheinz.dev/blog/85). Pod is restored but there is no activity or logs, basically I do not see any execution happening. 

First I tried with mysql following this [tutorial](https://phoenixnap.com/kb/kubernetes-mysql), and I see mysql process restored on exec'ing the container but I can not connect using mysql cli, I do not see any logs, CPU utilization is zero using top command. Then I tried with simple pod with a for loop.

### What did you expect to happen?

I expect restore pod to continue execution, but restore pod is hung.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a pod
```
root@n209-035-156:~/varungupta# cat hello-pod.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello
spec:
  containers:
    - name: hello-world-container
      image: busybox
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', "while :; do echo '.'; sleep 5 ; done"]
```

2. Checkpoint 
```
curl -XPOST "https://localhost:10250/checkpoint/default/hello-world/hello-world-container" --insecure --cert /var/run/kubernetes/client-kube-apiserver.crt --key /var/run/kubernetes/client-kube-apiserver.key
```

3. Create image, following this [tutorial](https://martinheinz.dev/blog/85).
buildah bud \
  --annotation=io.kubernetes.cri-o.annotations.checkpoint.name=hello \
  -t hello1:latest \
  Dockerfile .

4. Restore the pod
```
root@n209-035-156:~/varungupta# cat hello-restore.yaml 
apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello
spec:
  containers:
    - name: hello-world-container
      image: localhost/hello1:latest
      imagePullPolicy: IfNotPresent
      command: ['sh', '-c', "while :; do echo '.'; sleep 5 ; done"]
```

5. Expect to see logs, where as for initial pod I can see the logs.
<img width="546" alt="image" src="https://github.com/cri-o/cri-o/assets/12226243/b5b331cd-5061-4688-bab4-1aaf89ff7d51">

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.27.0
Version:        1.27.0
GitCommit:      b8764202e9ef38965ffbe469b8becd699889f5ca
GitCommitDate:  2023-06-06T22:27:43Z
GitTreeState:   clean
BuildDate:      2023-06-07T00:05:34Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  containers_image_ostree_stub
  containers_image_openpgp
  seccomp
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "25+",
    "gitVersion": "v1.25.6-dirty",
    "gitCommit": "ff2c119726cc1f8926fb0585c74b25921e866a28",
    "gitTreeState": "dirty",
    "buildDate": "2023-06-07T00:06:49Z",
    "goVersion": "go1.19",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v4.5.7",
  "serverVersion": {
    "major": "1",
    "minor": "25+",
    "gitVersion": "v1.25.6-dirty",
    "gitCommit": "ff2c119726cc1f8926fb0585c74b25921e866a28",
    "gitTreeState": "dirty",
    "buildDate": "2023-06-07T00:06:49Z",
    "goVersion": "go1.19",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

```console
$ criu --version
Version: 3.17.1
GitID: v3.17.1-13-g712cdbba0
```

```console
$ runc --version
runc version 1.1.3
commit: v1.1.3-0-g6724737f
spec: 1.0.2-dev
go: go1.17.10
libseccomp: 2.5.4
```
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ uname -a
Linux n209-035-156 5.4.56.bsk.9-amd64 #5.4.56.bsk.9 SMP Debian 5.4.56.bsk.9 Wed Aug 25 04:08:18 UTC 20 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
Physical
</details>
