### ISSUE TITLE
Deleted container never removed from crio_containers_oom_count_total

### ISSUE THREAD

**Issue by simonpasquier** [cri-o/cri-o#7249]
### What happened?

Using OCP (upcoming 4.14), I created a 10-replicas deployment with memory limits that trigger an immediate crash of the container. As expected the `crio_containers_oom_count_total` metric highlighted the problem.

After a while I've scaled down the deployment to 0 replicas.

### What did you expect to happen?

After scaling down the deployment, I expected the `crio_containers_oom_count_total` metric to disappear since all containers were now deleted.

### How can we reproduce it (as minimally and precisely as possible)?

Deployment example

```
kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-openshift
  namespace: test
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: 20Mi
```

Deploy the manifest, query the `crio_containers_oom_count_total` metric in Prometheus and check that it returns a few series.

Then scale down the deployment to 0 replicas. Query again the  `crio_containers_oom_count_total` metric.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
# paste output here
```

```console
$ kubectl version --output=json
# paste output here
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>
