### ISSUE TITLE
Example on userns docs does not match real behaviour

### ISSUE THREAD

**Issue by jsalatiel** [cri-o/cri-o#7301]
### What happened?

According to the [docs](https://github.com/cri-o/cri-o/blob/main/tutorials/userns.md) 

> RunAs{User,Group} and User Namespaces

>When RunAsUser or RunAsGroup are specified for a container in a pod, and the user namespace mode is "auto", the user namespace is configured to have that user inside of the user namespace, but the user in the host user namespace is in the range configured in /etc/subuid.
For instance, in RunAsUser is set to 1234 for a pod that specifies auto along with the /etc/subuid configuration above, the pod user inside the pod sees itself as 1234. However, from the perspective of the host, the pod user could actually be 101234.
This allows for the container process to think it is running as user 1234 for file access inside of the container, but actually be a much higher ID on the host.

This is my subuid:

```
# cat /etc/subuid 
containers:2130706432:16777216
# cat /etc/subgid 
containers:2130706432:16777216

```

Following that doc, this definition should be enough to explain the problem.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testns
  name: testns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testns
  template:
    metadata:
      labels:
        app: testns
      annotations:
        io.kubernetes.cri-o.userns-mode: "auto"
    spec:
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: wppvc
            readOnly: false
      containers:
      - name: shell
        command: ["sleep", "infinity"]
        image: debian
        volumeMounts:
        - name: mypvc
          mountPath: /testns

```
Applying that deployment definition, without the securityContext definition, from the host I can see that even when the container user appears to be root (id=0) the pods are running as a much higher user id at the host as expected from the
`io.kubernetes.cri-o.userns-mode: "auto"`

inside container:
```
/# id
uid=0(root) gid=0(root) groups=0(root)
# ps xau
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   2484   936 ?        Ss   15:53   0:00 sleep infinity

```

On the host:
```
**2130837+**  494306  0.0  0.0   2484   936 ?        Ss   12:53   0:00 sleep infinity
**2130903+**  494437  0.0  0.0   2484   932 ?        Ss   12:53   0:00 sleep infinity

```

Now I add the securityContext runAsUser: 1234

```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testns
  name: testns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testns
  template:
    metadata:
      labels:
        app: testns
      annotations:
        io.kubernetes.cri-o.userns-mode: "auto"
    spec:
      securityContext:
        runAsUser: 1234
      volumes:
        - name: mypvc
          persistentVolumeClaim:
            claimName: wppvc
            readOnly: false
      containers:
      - name: shell
        command: ["sleep", "infinity"]
        image: debian
        volumeMounts:
        - name: mypvc
          mountPath: /testns
```

From the container perspective, nothing has changed as expected
```
# id
uid=0(root) gid=0(root) groups=0(root)
/# ps xau
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   2484   932 ?        Ss   16:00   0:00 sleep infinity
```

But from the host the process appears to be running as 1234.
```
ps xau | grep sleep
1234      497791  0.0  0.0   2484   932 ?        Ss   13:00   0:00 sleep infinity
1234      497954  0.0  0.0   2484   892 ?        Ss   13:00   0:00 sleep infinity
```

Which does not match with the doc saying:

> For instance, in RunAsUser is set to 1234 for a pod that specifies auto along with the /etc/subuid configuration above, the pod user inside the pod sees itself as 1234. However, from the perspective of the host, the pod user could actually be 101234.
This allows for the container process to think it is running as user 1234 for file access inside of the container, but actually be a much higher ID on the host.

Or am I misinterpreting something?

### What did you expect to happen?

Docs to match the testing

### How can we reproduce it (as minimally and precisely as possible)?

yaml on the description

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.27.1
Version:        1.27.1
GitCommit:      65a8134d7c4722e1c39d0e1c473532a17c240682
GitCommitDate:  2023-07-12T18:25:19Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.20.2
Compiler:       gc
Platform:       linux/amd64
Linkmode:       static
BuildTags:      
  static
  netgo
  osusergo
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  seccomp
  apparmor
  selinux
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false

```

```console
$ kubectl version --output=json
 kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.5",
    "gitCommit": "93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c",
    "gitTreeState": "clean",
    "buildDate": "2023-08-24T00:48:26Z",
    "goVersion": "go1.20.7",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1",
  "serverVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.5",
    "gitCommit": "93e0d7146fb9c3e9f68aa41b2b4265b2fcdb0a4c",
    "gitTreeState": "clean",
    "buildDate": "2023-08-24T00:42:11Z",
    "goVersion": "go1.20.7",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# NAME="AlmaLinux"
VERSION="9.2 (Turquoise Kodkod)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.2 (Turquoise Kodkod)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"


$ uname -a
uname -a
Linux flat 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 29 17:06:27 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux

```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
kvm
</details>
