### ISSUE TITLE
Commands for keyless signature check do work

### ISSUE THREAD

**Issue by nicholasdille** [cri-o/cri-o#7465]
The commands for verifying the keyless cosign signature published in the GitHub release body stopped working because the signature is now created by a workflow located in `https://github.com/cri-o/packaging`. See the relevant data from [`search.sigstore.dev`](https://search.sigstore.dev/?hash=c8002a622e268b73f8d45b0adbdff9422b832106a23be137fabdc8a233b3f787) below.

The correct commands are now:

```bash
cosign verify-blob cri-o.amd64.v1.28.2.tar.gz \
    --certificate-identity https://github.com/cri-o/packaging/.github/workflows/obs.yml@refs/heads/main \
    --certificate-oidc-issuer https://token.actions.githubusercontent.com \
    --signature cri-o.amd64.v1.28.2.tar.gz.sig \
    --certificate cri-o.amd64.v1.28.2.tar.gz.cert
```

I will create a PR later today.

---------- 8< ----------

```yaml
data:
  Serial Number: '0x78835841fbc5f764fc5a388b19d1d4de9b07255c'
Signature:
  Issuer: O=sigstore.dev, CN=sigstore-intermediate
  Validity:
    Not Before: 4 days ago (2023-11-02T15:31:00+01:00)
    Not After: 4 days ago (2023-11-02T15:41:00+01:00)
  Algorithm:
    name: ECDSA
    namedCurve: P-256
  Subject:
    extraNames:
      items: {}
    asn: []
X509v3 extensions:
  Key Usage (critical):
  - Digital Signature
  Extended Key Usage:
  - Code Signing
  Subject Key Identifier:
  - D2:07:63:60:E4:41:71:6B:74:35:62:49:10:BA:AC:F1:9E:74:65:C9
  Authority Key Identifier:
    keyid: DF:D3:E9:CF:56:24:11:96:F9:A8:D8:E9:28:55:A2:C6:2E:18:64:3F
  Subject Alternative Name (critical):
    url:
    - https://github.com/cri-o/packaging/.github/workflows/obs.yml@refs/heads/main
  OIDC Issuer: https://token.actions.githubusercontent.com
  GitHub Workflow Trigger: workflow_dispatch
  GitHub Workflow SHA: d470fa00bbe4ed3ffd2b3e06246adac9bef40a0d
  GitHub Workflow Name: obs
  GitHub Workflow Repository: cri-o/packaging
  GitHub Workflow Ref: refs/heads/main
  OIDC Issuer (v2): https://token.actions.githubusercontent.com
  Build Signer URI: https://github.com/cri-o/packaging/.github/workflows/obs.yml@refs/heads/main
  Build Signer Digest: d470fa00bbe4ed3ffd2b3e06246adac9bef40a0d
  Runner Environment: github-hosted
  Source Repository URI: https://github.com/cri-o/packaging
  Source Repository Digest: d470fa00bbe4ed3ffd2b3e06246adac9bef40a0d
  Source Repository Ref: refs/heads/main
  Source Repository Identifier: '693295319'
  Source Repository Owner URI: https://github.com/cri-o
  Source Repository Owner Identifier: '29074118'
  Build Config URI: https://github.com/cri-o/packaging/.github/workflows/obs.yml@refs/heads/main
  Build Config Digest: d470fa00bbe4ed3ffd2b3e06246adac9bef40a0d
  Build Trigger: workflow_dispatch
  Run Invocation URI: https://github.com/cri-o/packaging/actions/runs/6733973023/attempts/1
  Source Repository Visibility At Signing: public
  1.3.6.1.4.1.11129.2.4.2: 04:7a:00:78:00:76:00:dd:3d:30:6a:c6:c7:11:32:63:19:1e:1c:99:67:37:02:a2:4a:5e:b8:de:3c:ad:ff:87:8a:72:80:2f:29:ee:8e:00:00:01:8b:90:71:d3:71:00:00:04:03:00:47:30:45:02:21:00:c1:f9:85:33:47:e9:12:48:1b:1a:5b:33:49:41:47:c5:f1:c7:34:a2:70:15:f6:b1:46:9d:c7:a7:4e:10:55:f5:02:20:06:79:33:c3:78:24:9c:45:f6:c4:a4:6b:1e:78:2b:83:ff:85:5a:ff:2b:ba:23:e8:7e:76:bf:45:ad:17:42:fc
```
