### ISSUE TITLE
The meaning of `runAsUser` in pod and in container

### ISSUE THREAD

**Issue by adelton** [cri-o/cri-o#7541]
### What happened?

I try to figure out the proper way of running user namespaced workloads on OpenShift. I use `io.kubernetes.cri-o.userns-mode` but there seems to be a weird difference in behaviour between `runAsuser` set on pod and in container.

I use OpenShift cluster (on ROSA hosted) 4.14 which seems to have cri-o-1.27.1-13.1.rhaos4.14.git956c5f7.el9.x86_64 installed on the worker nodes, `/etc/crio/crio.conf.d/00-default` configuring among others
```
[crio.runtime.workloads.openshift-builder]
activation_annotation = "io.openshift.builder"
allowed_annotations = [
  "io.kubernetes.cri-o.userns-mode",
  "io.kubernetes.cri-o.Devices"
]
```
and the nodes have
```
# cat /etc/subuid
core:100000:65536
containers:200000:16000000
```

When I give the `default` ServiceAccount in my namespace the `anyuid` SCC with
```
oc --context admin adm policy add-scc-to-user anyuid -n test-userns -z default
```

I can then run pod
```
apiVersion: v1
kind: Pod
metadata:
  name: test-userns
  annotations:
    io.openshift.builder: "true"
    io.kubernetes.cri-o.userns-mode: auto
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: registry.fedoraproject.org/fedora
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0
    command:
    - bash
    - -c
    - 'id ; cat /proc/self/uid_map ; echo --- ; cat /proc/self/gid_map ; trap : TERM INT; sleep infinity & wait'
```
and see
```
uid=0(root) gid=0(root) groups=0(root)
         0     200000      65536
---
         0     200000      65536
```

So the `spec.containers[*].securityContext.runAsUser` means the uid to run in the container. I've verified on the node that on the host the processes run with uid 200000 in this case.

However, when I move that
```
  securityContext:
    runAsUser: 0
```
out to the `spec` of the pod, I get
```
uid=0(root) gid=0(root) groups=0(root)
         1     200000      65535
         0          0          1
---
         0     200000      65536
```

One could easily assume that their processes run properly namespaced (and as 200000 on the host) when they in fact run as uid 0 on the host.

### What did you expect to happen?

I expect having
```
  securityContext:
    runAsUser: 0
```
in either the container or the pod `spec` to have the same or very similar effect, not this significantly different effect.

### How can we reproduce it (as minimally and precisely as possible)?

On an OCP 4.14, `oc apply`
```
apiVersion: v1
kind: Pod
metadata:
  name: test-userns
  annotations:
    io.openshift.builder: "true"
    io.kubernetes.cri-o.userns-mode: auto:map-to-root=false
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 0
  containers:
  - name: container
    image: registry.fedoraproject.org/fedora
    imagePullPolicy: IfNotPresent
    command:
    - bash
    - -c
    - 'id ; cat /proc/self/uid_map ; echo --- ; cat /proc/self/gid_map ; trap : TERM INT; sleep infinity & wait'
```

### Anything else we need to know?

One might say -- don't touch pod's `spec.securityContext` and do it all on the container level.

The problem is that to use `private:uidmapping=...`, one has to set the pod's `spec.securityContext.runAsUser` or one hits https://github.com/cri-o/cri-o/issues/7540.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.27.1-13.1.rhaos4.14.git956c5f7.el9
Version:        1.27.1-13.1.rhaos4.14.git956c5f7.el9
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
GoVersion:      go1.20.10
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  rpm_crashtraceback
  libtrust_openssl
  selinux
  seccomp
  exclude_graphdriver_devicemapper
  exclude_graphdriver_btrfs
  containers_image_ostree_stub
LDFlags:           -compressdwarf=false -B 0xfcd4976dd7077fe35cc67cb01fcf2b8ec376fcaa -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 '
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.4",
    "gitCommit": "9b1e0d27df3cf7b2ea878cd668ce709cc4e4c41a",
    "gitTreeState": "clean",
    "buildDate": "2023-11-03T10:55:50Z",
    "goVersion": "go1.20.10 X:strictfipsruntime",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1"
}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="414.92.202311150705-0"
VERSION_ID="4.14"
VARIANT="CoreOS"
VARIANT_ID=coreos
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 414.92.202311150705-0 (Plow)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.14/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.14"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.14"
OPENSHIFT_VERSION="4.14"
RHEL_VERSION="9.2"
OSTREE_VERSION="414.92.202311150705-0"
$ uname -a
Linux ip-10-0-7-205 5.14.0-284.41.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 9 13:57:27 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
OCP 4.14 on ROSA hosted.
</details>
