### ISSUE TITLE
Container in user namespaced pod cannot write volume

### ISSUE THREAD

**Issue by adelton** [cri-o/cri-o#7542]
### What happened?

I try to figure out the proper way of running user namespaced workloads on OpenShift. I use `io.kubernetes.cri-o.userns-mode` and it mostly works (see https://github.com/cri-o/cri-o/issues/7540 and https://github.com/cri-o/cri-o/issues/7541 for some small, maybe documentation, issues) but the namespaced pods don't seem to be able to write to the volumes and no mechanism to enable that seems available.

On an OpenShift cluster (on ROSA hosted) 4.14 with cri-o-1.27.1-13.1.rhaos4.14.git956c5f7.el9.x86_64 installed on the worker nodes I am able to run user namespaced pod like
```
apiVersion: v1
kind: Pod
metadata:
  name: test-userns
  annotations:
    io.openshift.builder: "true"
    io.kubernetes.cri-o.userns-mode: auto
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: registry.fedoraproject.org/fedora
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0
    command:
    - bash
    - -c
    - 'id ; cat /proc/self/uid_map ; trap : TERM INT; sleep infinity & wait'
```
and I get
```
uid=0(root) gid=0(root) groups=0(root)
         0     200000      65536
```
in the logs and I also verified on the worker host that the process runs as uid 200000 on the host.

So I added a PersistentVolumeClaim, volume, and volumeMount.

### What did you expect to happen?

I expected the namespaced root to be able to work with the volume as root should.

### How can we reproduce it (as minimally and precisely as possible)?

On an OCP cluster, create PVC and Pod from
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-userns-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-userns
  annotations:
    io.openshift.builder: "true"
    io.kubernetes.cri-o.userns-mode: auto
spec:
  restartPolicy: Never
  containers:
  - name: container
    image: registry.fedoraproject.org/fedora
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0 
    command:
    - bash
    - -c
    - 'id ; cat /proc/self/uid_map ; mount | grep /var/lib/data ; ls -la /var/lib/data ; touch /var/lib/data/test ; trap : TERM INT; sleep infinity & wait'
    volumeMounts:
    - mountPath: /var/lib/data
      name: test-userns-dir
  volumes:
  - name: test-userns-dir
    persistentVolumeClaim:
      claimName: test-userns-data
```

Check `oc logs pod/test-userns` -- it shows
```
uid=0(root) gid=0(root) groups=0(root)
         0     200000      65536
/dev/nvme2n1 on /var/lib/data type ext4 (rw,relatime,seclabel)
total 20
drwxr-xr-x. 3 nobody nobody  4096 Dec  4 11:38 .
drwxr-xr-x. 1 root   root      18 Dec  4 11:38 ..
drwx------. 2 nobody nobody 16384 Dec  4 11:38 lost+found
touch: cannot touch '/var/lib/data/test': Permission denied
```

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.27.1-13.1.rhaos4.14.git956c5f7.el9
Version:        1.27.1-13.1.rhaos4.14.git956c5f7.el9
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
GoVersion:      go1.20.10
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  rpm_crashtraceback
  libtrust_openssl
  selinux
  seccomp
  exclude_graphdriver_devicemapper
  exclude_graphdriver_btrfs
  containers_image_ostree_stub
LDFlags:           -compressdwarf=false -B 0xfcd4976dd7077fe35cc67cb01fcf2b8ec376fcaa -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 '
SeccompEnabled:   true
AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.4",
    "gitCommit": "9b1e0d27df3cf7b2ea878cd668ce709cc4e4c41a",
    "gitTreeState": "clean",
    "buildDate": "2023-11-03T10:55:50Z",
    "goVersion": "go1.20.10 X:strictfipsruntime",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1"
}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="414.92.202311150705-0"
VERSION_ID="4.14"
VARIANT="CoreOS"
VARIANT_ID=coreos
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 414.92.202311150705-0 (Plow)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.14/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.14"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.14"
OPENSHIFT_VERSION="4.14"
RHEL_VERSION="9.2"
OSTREE_VERSION="414.92.202311150705-0"
$ uname -a
Linux ip-10-0-7-205 5.14.0-284.41.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 9 13:57:27 EST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
OCP 4.14 on ROSA hosted. 
</details>
