### ISSUE TITLE
provision Pod/Container with local Timezone during runtime

### ISSUE THREAD

**Issue by alireza-taleghani-stratsys** [cri-o/cri-o#7550]
Following OCI common spec we could instruct Containers to respect local TZ accordingly...
while podman and some other OCI complient clients (assume utilizing crun under the hood) follow common containers configuration as following Container runtime is able to report date/time with correct timezone indeed

```bash
# /etc/containers/containers.conf
...
[containers]
#tz="UTC"
tz = "Europe/Stockholm"
...
```
- ref: https://github.com/containers/common/blob/d0a7910051b13fe6cc69ca8efeee1d7e0005b4cd/pkg/config/containers.conf#L274

usage without/with configuration file/entry inplace:

```bash
$ podman run --rm -it docker.io/library/debian:jessie date
Tue Dec  5 09:21:36 CET 2023

# set tz=CET on [ /etc/containers/containers.conf ] 

$ podman run --rm -it docker.io/library/debian:jessie date
Tue Dec  5 08:21:46 UTC 2023
```

having that inplace will help us to have all pods/containers report the write timestamp on logs/msg without any need of extra env/volume mount as instructed here and there...

```yaml
# TZ via ENV
spec:
  containers:
  - name: my-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: TZ
      value: "America/Toronto"
```

```yaml
# TZ via Volume
spec:
  containers:
  - name: my-container
    image: gcr.io/google-samples/node-hello:1.0
    volumeMounts:
    - name: tz-config
      mountPath: /etc/localtime
  volumes:
    - name: tz-config
      hostPath:
        path: /usr/share/zoneinfo/America/Toronto
        type: File
```
