### ISSUE TITLE
Containers running in user namespaces

### ISSUE THREAD

**Issue by rgherta** [cri-o/cri-o#7568]
### What happened?

Tried reproducing the steps in https://github.com/cri-o/cri-o/blob/main/tutorials/userns.md and I get the following error _Error: open /proc/0/uid_map: no such file or directory_

### What did you expect to happen?

I expect a stateless container running in userspace

### How can we reproduce it (as minimally and precisely as possible)?

Fedora 39, kubernetes 1.27 provisioned with kubeadm, crio 1.27, kubelet 1.27 with cgroupv2 and systemd as cgroup manager
Kubernetes is provisioned with feature UserNamespacesStatelessPodsSupport=true enabled on both master and worker kubelets

Just follow steps in tutorial

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.27.1
Version:        1.27.1
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
GoVersion:      go1.21rc3
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
  rpm_crashtraceback
  seccomp
  selinux
LDFlags:           -X github.com/cri-o/cri-o/version=1.27.1 -B 0x203b3894c21011e72584058cf5600b55621c0f89 -compressdwarf=false -linkmode=external -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  '
SeccompEnabled:   true
AppArmorEnabled:  false

```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.8",
    "gitCommit": "66fee42707cd7f5a89f1987f7cb81b02dd19161c",
    "gitTreeState": "archive",
    "buildDate": "2023-11-19T00:00:00Z",
    "goVersion": "go1.21.4",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.1",
  "serverVersion": {
    "major": "1",
    "minor": "27",
    "gitVersion": "v1.27.0",
    "gitCommit": "1b4df30b3cdfeaba6024e81e559a6cd09a089d65",
    "gitTreeState": "clean",
    "buildDate": "2023-04-11T17:04:24Z",
    "goVersion": "go1.20.3",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation

$ uname -a
Linux master1 6.5.12-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:44:24 UTC 2023 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
nodes provisioned with kvm 
</details>

**Comment by rgherta** [comment]
attaching also the kubelet error that migth be relevant

```
Dec 09 15:53:45 worker1 kubelet[10157]: E1209 15:53:45.385898   10157 remote_runtime.go:302] "CreateContainer in sandbox from runtime service failed" err="rpc error: code = Unknown desc = open /proc/0/uid_map: no such file or directory" podSandboxID="63aa9dee1c3effb58da4023cdb4acfcc971780c15af58fcb2a32c155c203a4f3"
Dec 09 15:53:45 worker1 kubelet[10157]: E1209 15:53:45.386009   10157 kuberuntime_manager.go:1212] container &Container{Name:fedora,Image:fedora/fedora:latest,Command:[],Args:[sleep infinity],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:,HostPort:0,ContainerPort:80,Protocol:TCP,HostIP:,},},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-api-access-f9grj,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:Always,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},} start failed in pod userns_default(848f979c-0556-4011-973f-fef91f92303a): CreateContainerError: open /proc/0/uid_map: no such file or directory
```

**Comment by rgherta** [comment]
Oh no... sorry guys.... I restated kubelet on worker node without UserNamespacesStatelessPodsSupport=true  and this tim the process is running in the correct uid range.... Apparently this feature does not agree with CRI-O, although the cluster has the right to schedule workload with proper configuration.... Let me know what plans you have for this and if I should ignore this feature.

**Comment by rgherta** [comment]
nope, it s me again... I have in /etc/subuid and /etc/subgid

```
roman@worker1:~$ cat /etc/subuid
roman:524288:165536
containers:1000000:1000000
```

So when I create the following 3 pods

```
[user@fedora ~]$ kubectl apply -f - <<EOF
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: fedora
    image: fedora/fedora:latest
    args: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-userns-1
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto"
spec:
  containers:
  - name: fedora
    image: fedora/fedora:latest
    args: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-userns-2
  annotations:
    io.kubernetes.cri-o.userns-mode: "auto"
spec:
  containers:
  - name: fedora
    image: fedora/fedora:latest
    args: ["sleep", "infinity"]
---
EOF
```

one of the 2 rootless pods is never creating throwing this error

```
  Warning  FailedCreatePodSandBox  2s (x22 over 4m32s)  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = creating pod sandbox with name "k8s_test-pod-userns-2_default_a00701ce-9777-40b8-8b39-153e5baf5e11_0": not enough unused IDs in user namespace
```
