### ISSUE TITLE
Default registry when using image volumes

### ISSUE THREAD

**Issue by rhuss** [cri-o/cri-o#8780]
With the new support for OCI image volumes I ran into this error when using an image without an explicit OCI registry part:

Using the Pod

```yaml
kind: Pod
metadata:
  name: image-volume-demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "sleep infinity"]
    volumeMounts:
    - mountPath: /mnt/models
      name: model-volume
      subPath: /models
  volumes:
  - name: model-volume
    image:
      reference: rhuss/caikit-flan-t5-small
```

led to 

```
Warning  Failed     6s (x2 over 19s)  kubelet            
Failed to pull image "rhuss/caikit-flan-t5-small": 
initializing source docker://quay.io/rhuss/caikit-flan-t5-small:latest: 
reading manifest latest in quay.io/rhuss/caikit-flan-t5-small: unauthorized: access to the requested resource is not authorized
```

which hints that `quay.io` is used as the default registry. However, all other parts of K8s (i.e., the `image:` field in the Pod Spec) use `docker.io` as the default registry. Using `docker.io/rhuss/caikit-flan-t5-small` fixed this issue.

I think this should be at least consistent.

**Comment by saschagrunert** [comment]
This looks like a configuration "issue". Do you mind sharing the CRI-O logs? If you configure `/etc/containers/registries.conf` like this, then it should work:

```toml
[registries.block]
registries = []

[registries.insecure]
registries = []

[registries.search]
registries = ["docker.io", "quay.io"]
```
