### ISSUE TITLE
[NetworkPluginNotReady] Probe don't work is pods

### ISSUE THREAD

**Issue by ilusha0561h** [cri-o/cri-o#9074]
### What happened?

│   Warning  Unhealthy  8m9s (x258 over 48m)   kubelet  Readiness probe errored: rpc error: code = Unknown desc = command error: EOF, stdout: , stderr: , exit code -1                                          ││   Warning  Unhealthy  3m6s (x270 over 47m)   kubelet  Liveness probe errored: rpc error: code = Unknown desc = command error: EOF, stdout: , stderr: , exit code -1  

calicio

### What did you expect to happen?

work

### How can we reproduce it (as minimally and precisely as possible)?

kube-system          calico-kube-controllers-d4544f494-r28m8                           0/1     Running                    2                   28h
kube-system          calico-node-77knt                                                 0/1     Running                    2                   28h

### Anything else we need to know?

probes in kubernetes stopped working

### CRI-O and Kubernetes version

<details>

```console
crio version 1.32.2
   GitCommit:      318db72eb0b3d18c22c995aa7614a13142287296
   GitCommitDate:  2025-03-02T18:05:31Z
   GitTreeState:   dirty
   BuildDate:      1970-01-01T00:00:00Z
   GoVersion:      go1.23.3
   Compiler:       gc
   Platform:       linux/amd64
   Linkmode:       static
   BuildTags:
     static
     netgo
     osusergo
     exclude_graphdriver_btrfs
     seccomp
     apparmor
     selinux
     exclude_graphdriver_devicemapper
   LDFlags:          unknown
   SeccompEnabled:   true
   AppArmorEnabled:  true
```

```console
crio version 1.32.2
   GitCommit:      318db72eb0b3d18c22c995aa7614a13142287296
   GitCommitDate:  2025-03-02T18:05:31Z
   GitTreeState:   dirty
   BuildDate:      1970-01-01T00:00:00Z
   GoVersion:      go1.23.3
   Compiler:       gc
   Platform:       linux/amd64
   Linkmode:       static
   BuildTags:
     static
     netgo
     osusergo
     exclude_graphdriver_btrfs
     seccomp
     apparmor
     selinux
     exclude_graphdriver_devicemapper
   LDFlags:          unknown
   SeccompEnabled:   true
   AppArmorEnabled:  true
(base) root@mla100x2:/home/devops# kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "32",
    "gitVersion": "v1.32.3",
    "gitCommit": "32cc146f75aad04beaaa245a7157eb35063a9f99",
    "gitTreeState": "clean",
    "buildDate": "2025-03-11T19:58:53Z",
    "goVersion": "go1.23.6",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.5.0",
  "serverVersion": {
    "major": "1",
    "minor": "32",
    "gitVersion": "v1.32.3",
    "gitCommit": "32cc146f75aad04beaaa245a7157eb35063a9f99",
    "gitTreeState": "clean",
    "buildDate": "2025-03-11T19:52:21Z",
    "goVersion": "go1.23.6",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

</details>

### OS version

<details>

```console
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
(base) root@mla100x2:/home/devops# uname -a
Linux mla100x2 5.15.0-134-generic #145-Ubuntu SMP Wed Feb 12 20:08:39 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>
physical
</details>

**Comment by ilusha0561h** [comment]
```
    livenessProbe:
      exec:
        command:
        - /bin/calico-node
        - -felix-live
        - -bird-live
      failureThreshold: 6
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    name: calico-node
    readinessProbe:
      exec:
        command:
        - /bin/calico-node
        - -felix-ready
        - -bird-ready
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
```
