### ISSUE TITLE
Support CNAI OCI artifact models

### ISSUE THREAD

**Issue by chlins** [cri-o/cri-o#9127]
### What happened?

It seems that the CRI-O has supported mount OCI Artifact in the main branch, but I ran into the issue when mount the artifact which bundled the AI models into it. The mount action is success, but cannot list the accurate files in pod.

### What did you expect to happen?

Mount the OCI Artifact into the pod and can list the accurate files in the pod mount path.

### How can we reproduce it (as minimally and precisely as possible)?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: image-volume
spec:
  containers:
  - name: shell
    command: ["sleep", "infinity"]
    image: debian
    volumeMounts:
    - name: volume
      mountPath: /tmp/model
  volumes:
  - name: volume
    image:
      reference: ghcr.io/chlins/qwen:v1
      pullPolicy: Always
```

Exec into the pod and ls the `/tmp/model`.

### CRI-O and Kubernetes version

<details>

```console
$ crio --version
crio version 1.33.0
   GitCommit:      3e6b6cf8237166a6424a6d319c29a99c22f1e9ed
   GitCommitDate:  2025-03-28T10:58:57Z
   GitTreeState:   clean
   BuildDate:      2025-03-31T12:11:30Z
   GoVersion:      go1.24.1
   Compiler:       gc
   Platform:       linux/amd64
   Linkmode:       dynamic
   BuildTags:
     containers_image_ostree_stub
     seccomp
     selinux
   LDFlags:          unknown
   SeccompEnabled:   true
   AppArmorEnabled:  false
```

```console
$ kubectl version --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "31",
    "gitVersion": "v1.31.0",
    "gitCommit": "9edcffcde5595e8a5b1a35f88c421764e575afce",
    "gitTreeState": "clean",
    "buildDate": "2024-08-13T07:37:34Z",
    "goVersion": "go1.22.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.4.2",
  "serverVersion": {
    "major": "1",
    "minor": "31",
    "gitVersion": "v1.31.1",
    "gitCommit": "948afe5ca072329a73c8e79ed5938717a5cb3d21",
    "gitTreeState": "clean",
    "buildDate": "2024-09-11T21:22:08Z",
    "goVersion": "go1.22.6",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
$ uname -a
Linux c3-small-x86-01 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
```

</details>

### Additional environment details (AWS, VirtualBox, physical, etc.)

<details>

</details>
