### ISSUE TITLE
Image volume `subPath` does not work with OCI artifacts

### ISSUE THREAD

**Issue by saschagrunert** [cri-o/cri-o#9155]
`subPath` only works for images, not for OCI artifacts like: 

```
---
apiVersion: v1
kind: Pod
metadata:
  name: image-volume
spec:
  containers:
  - name: shell
    command: ["sleep", "infinity"]
    image: debian
    volumeMounts:
    - name: vv
      subPath: cri-o
      mountPath: /v
  volumes:
  - name: vv
    image:
      reference: ghcr.io/cri-o/bundle:latest-amd64
      pullPolicy: IfNotPresent
```

```
> k exec -it image-volume -- ls /v
cri-o
```

We probably have to extend our integration tests for sub path support as well side by side to this fix.
